Feature: Dedicated hosts and host groups
IBM-Cloud/terraform-provider-ibm pull request #2357
Opened 2021-03-15 13:14 UTC by deepaksibm

2021-03-15 13:15 UTC, deepaksibm commented
<img width="467" alt="Screen Shot 2021-03-15 at 5 21 32 PM" src="https://user-images.githubusercontent.com/77007253/111158856-87968080-85be-11eb-9764-adb08031a963.png">
<img width="467" alt="Screen Shot 2021-03-15 at 5 22 10 PM" src="https://user-images.githubusercontent.com/77007253/111158866-8a917100-85be-11eb-82e4-06ce09194044.png">
<img width="467" alt="Screen Shot 2021-03-15 at 5 23 26 PM" src="https://user-images.githubusercontent.com/77007253/111158877-8b2a0780-85be-11eb-81dd-2f7f56b28f06.png">
<img width="467" alt="Screen Shot 2021-03-15 at 5 25 11 PM" src="https://user-images.githubusercontent.com/77007253/111158882-8bc29e00-85be-11eb-9343-540779c7aef1.png">
<img width="467" alt="Screen Shot 2021-03-15 at 6 01 56 PM" src="https://user-images.githubusercontent.com/77007253/111158888-8c5b3480-85be-11eb-909f-b36de6a7cced.png">
<img width="467" alt="Screen Shot 2021-03-15 at 6 04 24 PM" src="https://user-images.githubusercontent.com/77007253/111158893-8cf3cb00-85be-11eb-9b31-380d25f31d68.png">
<img width="467" alt="Screen Shot 2021-03-15 at 6 06 30 PM" src="https://user-images.githubusercontent.com/77007253/111158897-8d8c6180-85be-11eb-882d-a026d735a56f.png">
<img width="467" alt="Screen Shot 2021-03-15 at 6 11 37 PM" src="https://user-images.githubusercontent.com/77007253/111158903-8e24f800-85be-11eb-8a81-11fc8652f4cd.png">
<img width="467" alt="Screen Shot 2021-03-15 at 6 13 23 PM" src="https://user-images.githubusercontent.com/77007253/111158907-8ebd8e80-85be-11eb-9c42-5acd5c6c3f92.png">

2021-03-15 13:15 UTC, deepaksibm commented
Terraform Show:

https://ibm.box.com/s/xuf88yxt587s80l8u7wdxhcmlxv1ri6a

2021-03-15 14:19 UTC, mayukh-sarkar-1 requested changes

2021-03-16 07:59 UTC, deepaksibm commented on website/docs/r/is_dedicated_host.html.markdown
>  sidebar_current: "docs-ibm-resource-is-dedicated-host"
Removed.

2021-03-16 08:00 UTC, deepaksibm commented on website/docs/r/is_dedicated_host.html.markdown
>  page_title: "IBM : is_dedicated_host"
Added.

2021-03-16 10:47 UTC, hkantare commented on ibm/resource_ibm_is_dedicated_host_group_test.go
> +	name := fmt.Sprintf("name%d", acctest.RandIntRange(10, 100))
same as above comment add the prefix tfXXX for the name

2021-03-16 10:47 UTC, hkantare commented on website/docs/r/is_dedicated_host.html.markdown
> +  profile = "dh2-56x464"
format the example sample code

2021-03-16 10:47 UTC, hkantare commented on website/docs/r/is_dedicated_host.html.markdown
> +* `host_group` - (Optional, string) The unique identifier of the dedicated host group for this dedicated host.
is the host_group a optional or required?

2021-03-16 10:47 UTC, hkantare commented on website/docs/r/is_dedicated_host.html.markdown
> +* `instances` - Array of instances that are allocated to this dedicated host.
Give the inner attributes of the instances

2021-03-16 10:47 UTC, hkantare commented on website/docs/r/is_dedicated_host.html.markdown
> +* `zone` - The zone this dedicated host resides in.
Add the import section also

2021-03-16 10:47 UTC, hkantare commented on website/docs/r/is_dedicated_host_group.html.markdown
> +* `zone` - The zone this dedicated host resides in.
Add the import section

2021-03-23 14:33 UTC, deepaksibm commented on ibm/resource_ibm_is_dedicated_host.go
> +				Optional:    true,
added validation

2021-03-23 14:33 UTC, deepaksibm commented on ibm/resource_ibm_is_dedicated_host.go
> +	d.SetId(*dedicatedHost.ID)
added wait logic

2021-03-24 04:35 UTC, merged