Compliance terraform scripts.
IBM-Cloud/terraform-provider-ibm pull request #3076
Opened 2021-09-07 13:39 UTC by Rakesh-Polepeddi

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2021-09-17 07:30 UTC, ashishth09 commented on examples/ibm-posture-management/README.md
> +# Example for PostureManagementV1
Let's have the example inside top-level ibm-scc directory

ibm-scc
 - findings (we already added that)
 - posture-management
 - admin 
etc to have all the scc things in one place

2021-09-17 07:31 UTC, ashishth09 commented on website/docs/d/list_latest_scans.html.markdown
> +subcategory: "Posture Management"
Please use subcategory as Security and Compliance Center (SCC)

example - https://github.com/IBM-Cloud/terraform-provider-ibm/pull/3043/files#diff-d7a9dc26502531b3cbb5781353d133fc00bf67e3deca341b2fb5225ccd58ebeeR3

2021-09-21 10:14 UTC, ashishth09 commented on website/allowed-subcategories.txt
>  Security and Compliance Center (SCC)
@Rakesh-Polepeddi we checked with our DOC team and was asked to use Security and Compliance Center alone and not have Security and Compliance Center (SCC). Let's remove `Posture Management` from this file and also (SCC) just keep  Security and Compliance Center

2021-09-21 10:15 UTC, ashishth09 commented on website/docs/d/list_profiles.html.markdown
> +subcategory: "Security and Compliance Center (SCC)"
This should be just Security and Compliance Center based on new comments from our doc team.

2021-09-21 10:15 UTC, ashishth09 commented on website/docs/d/list_profiles.html.markdown
> +subcategory: "Security and Compliance Center (SCC)"
Please check other places also

2021-09-21 14:28 UTC, ashishth09 requested changes
Names are not proper, let's use ibm_scc_posture as prefix and resource doesn't need to have the verb in it as in ibm_*list*_scopes.  ibm_scc_posture_scopes as a data source conveys the meaning that you want to list the scopes


                       "ibm_list_scopes":       ibm_scc_posture_scopes
			"ibm_list_latest_scans": ibm_scc_posture_latest_scans
			"ibm_list_profiles":     ibm_scc_posture_profiles
			"ibm_scans_summary":     ibm_scc_posture_scan_summary
			"ibm_scan_summaries":    ibm_scc_posture_scan_summaries

2021-09-22 04:01 UTC, Rakesh-Polepeddi commented
> Names are not proper, let's use ibm_scc_posture as prefix and resource doesn't need to have the verb in it as in ibm__list__scopes. ibm_scc_posture_scopes as a data source conveys the meaning that you want to list the scopes
> 
> ```
>                    "ibm_list_scopes":       ibm_scc_posture_scopes
> 		"ibm_list_latest_scans": ibm_scc_posture_latest_scans
> 		"ibm_list_profiles":     ibm_scc_posture_profiles
> 		"ibm_scans_summary":     ibm_scc_posture_scan_summary
> 		"ibm_scan_summaries":    ibm_scc_posture_scan_summaries
> ```

This issue is addressed

2021-09-22 04:03 UTC, Rakesh-Polepeddi commented
> Names are not proper, let's use ibm_scc_posture as prefix and resource doesn't need to have the verb in it as in ibm__list__scopes. ibm_scc_posture_scopes as a data source conveys the meaning that you want to list the scopes
> 
> ```
>                    "ibm_list_scopes":       ibm_scc_posture_scopes
> 		"ibm_list_latest_scans": ibm_scc_posture_latest_scans
> 		"ibm_list_profiles":     ibm_scc_posture_profiles
> 		"ibm_scans_summary":     ibm_scc_posture_scan_summary
> 		"ibm_scan_summaries":    ibm_scc_posture_scan_summaries
> ```

This comment is addressed

2021-09-22 05:29 UTC, ashishth09 commented on examples/ibm-scc/posture-management/README.md
> +data "list_scopes" "list_scopes_instance" {
This needs to follow the new name changes of ibm_scc_XXX

2021-09-22 05:54 UTC, ashishth09 commented on ibm/data_source_ibm_list_scopes_test.go
> +// Copyright IBM Corp. 2021 All Rights Reserved.
File names should match the resource name as well. It should be
data_source_ibm_scc_posture_scopes.go

2021-09-22 10:54 UTC, ashishth09 commented on website/docs/d/list_profiles.html.markdown
> +---
These file names should be changed as well to scc_posture_profiles.. basically from the resource name which is

ibm_scc_posture_profiles drop the ibm  so the above file will become scc_posture_profiles.html.markdown. Check other documention files as well

2021-09-22 11:07 UTC, Rakesh-Polepeddi commented on examples/ibm-scc/posture-management/variables.tf
> +  default     = "262"
remove the defaults.

2021-09-24 04:39 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_latest_scans.html.markdown
> +Provides a read-only data source for list_latest_scans. You can then reference the fields of the data source in other resources within the same configuration using interpolation syntax.
Provides a read-only data source for list_latest_scans. You can then reference the fields of the data source in other resources within the same configuration using interpolation syntax.

as

Review information about the security and compliance center posture latest scans. For more information, about  ..., see []().

2021-09-24 04:40 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_latest_scans.html.markdown
> +## Example Usage
U in Usage to be as usage

2021-09-24 04:40 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_latest_scans.html.markdown
> +```hcl
The code hcl to be as terraform

2021-09-24 04:40 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_latest_scans.html.markdown
> +## Argument Reference
R in Reference should be reference

2021-09-24 04:41 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_latest_scans.html.markdown
> +* `id` - The unique identifier of the list_latest_scans.
list_latest_scans should be in code tag as `list_latest_scans`

2021-09-24 04:43 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_latest_scans.html.markdown
> +	  * Constraints: Allowable values are: standard, authored, custom, standard_cv, temmplategroup, standard_certificate
Supported values are **standard**, **authored**, **custom**, **standard_cv**, **temmplategroup**, **standard_certificate**.

check the spelling and naming convention of **temmplategroup**

2021-09-24 04:45 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_profiles.html.markdown
> +Provides a read-only data source for list_profiles. You can then reference the fields of the data source in other resources within the same configuration using interpolation syntax.
The description should have full name, can be rewritten as

Review information about Security and Compliance Center list profiles. For more information, about list profiles, see []().

2021-09-24 04:45 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_profiles.html.markdown
> +```hcl
hcl to be terraform

2021-09-24 04:46 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_profiles.html.markdown
> +## Argument Reference
R to be as r

2021-09-24 04:46 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_profiles.html.markdown
> +## Attribute Reference
R to be as r

2021-09-24 04:47 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_profiles.html.markdown
> +		* `os_details` - (Optional, List) The operatoring system that the profile applies to.
operatoring system   should be Operating System

2021-09-24 04:47 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_profiles.html.markdown
> +		* `environment` - (Optional, List) A list of environments that a profile can be applied to.
Nested argument must be in alphatical order

2021-09-24 04:48 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_profiles.html.markdown
> +	* `name` - (Optional, String) The name of the profile.
Nested scheme to be in alphabetic order.

2021-09-24 04:50 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_profiles.html.markdown
> +	  * Constraints: Allowable values are: predefined, custom, template_group
* Constraints: Allowable values are: predefined, custom, template_group
1. is Constraints part of the profile_type, if yes, then Nested scheme....... details should be added.
2. descrption : Supported values are **predefined**, **custom**, **template_group**

2021-09-24 04:52 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scan_summaries.html.markdown
> +Provides a read-only data source for scan_summaries. You can then reference the fields of the data source in other resources within the same configuration using interpolation syntax.
1. Provides a read-only data source for scan_summaries.
as
Review information of Security and Compliance Center scan summaries. 

2. Add reference link of scan summaries

2021-09-24 04:52 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scan_summaries.html.markdown
> +## Example Usage
U should be u

2021-09-24 04:52 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scan_summaries.html.markdown
> +```hcl
The hcl should be terraform

2021-09-24 04:52 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scan_summaries.html.markdown
> +## Argument Reference
R to be as r

2021-09-24 04:52 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scan_summaries.html.markdown
> +## Attribute Reference
R to be as r

2021-09-24 04:53 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scan_summaries.html.markdown
> +* `profile_id` - (Required, String) The profile ID. This can be obtained from the Security and Compliance Center UI by clicking on the profile name. The URL contains the ID.
UI to be as console

2021-09-24 04:53 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scan_summaries.html.markdown
> +* `scope_id` - (Required, String) The scope ID. This can be obtained from the Security and Compliance Center UI by clicking on the scope name. The URL contains the ID.
UI to be as console

2021-09-24 04:53 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scan_summaries.html.markdown
> +* `first` - (Optional, List) he URL of the first scan summary.
T missing in The

2021-09-24 04:55 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scan_summaries.html.markdown
> +	  * Constraints: Allowable values are: pending, discovery_started, discovery_completed, error_in_discovery, gateway_aborted, controller_aborted, not_accepted, waiting_for_refine, validation_started,
1. if Constraints part of status, we need to add nested schema.....
2. Supported values are  .....   the values need to be in bold

2021-09-24 04:56 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scan_summaries.html.markdown
> +		  * Constraints: Allowable values are: standard, authored, custom, standard_cv, temmplategroup, standard_certificate
1. If constraints part of profilte_type, we need to add Nested scheme..... and 
2. Supported values are ....   the values should be marked as bold

2021-09-24 04:57 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scan_summaries.html.markdown
> +		  * Constraints: Allowable values are: standard, authored, custom, standard_cv, temmplategroup, standard_certificate
If constraints part of profilte_type, we need to add Nested scheme..... and
Supported values are .... the values should be marked as bold

2021-09-24 04:57 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scan_summaries.html.markdown
> +			  * Constraints: Allowable values are: standard, authored, custom, standard_cv, temmplategroup, standard_certificate
If constraints part of profilte_type, we need to add Nested scheme..... and
Supported values are .... the values should be marked as bold

2021-09-24 04:59 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scans_summary.html.markdown
> +Provides a read-only data source for scans_summary. You can then reference the fields of the data source in other resources within the same configuration using interpolation syntax.
1. Review information of Security and Compliance Center posture scan summary. 
2. Add reference link for posture scan summary

2021-09-24 04:59 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scans_summary.html.markdown
> +## Example Usage
Change U as u

2021-09-24 04:59 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scans_summary.html.markdown
> +```hcl
hcl as terraform

2021-09-24 04:59 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scans_summary.html.markdown
> +## Argument Reference
R as r

2021-09-24 05:00 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scans_summary.html.markdown
> +* `scan_id` - (Required, Forces new resource, String) Your Scan ID.
The scan ID

2021-09-24 05:00 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scans_summary.html.markdown
> +## Attribute Reference
R as r

2021-09-24 05:00 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scans_summary.html.markdown
> +	  * Constraints: Allowable values are: pass, unable_to_perform
If constraints part of profilte_type, we need to add Nested scheme..... and
Supported values are .... the values should be marked as bold

2021-09-24 05:00 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scans_summary.html.markdown
> +		  * Constraints: Allowable values are: pass, fail
If constraints part of status, we need to add Nested scheme..... and
Supported values are .... the values should be marked as bold

2021-09-24 05:01 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scans_summary.html.markdown
> +			  * Constraints: Allowable values are: pass, unable_to_perform
If constraints part of resource_status, we need to add Nested scheme..... and
Supported values are .... the values should be marked as bold

2021-09-24 05:02 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scans_summary.html.markdown
> +			* `resource` - (Optional, List) A list of resources that a profile can be used with.
argument in the nested scheme to be order alphabetically

2021-09-24 05:03 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scans_summary.html.markdown
> +				* `name` - (Optional, String)
Description to be entered for the name and version.

2021-09-24 05:03 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scans_summary.html.markdown
> +			Nested scheme for **os_details**:
Description to be entered for the name and version.

2021-09-24 05:04 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scans_summary.html.markdown
> +		* `resource_not_applicable_count` - (Optional, Integer) The resource count of not applicable(na) controls.
(na) -. (NA)

2021-09-24 05:05 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scopes.html.markdown
> +Provides a read-only data source for list_scopes. You can then reference the fields of the data source in other resources within the same configuration using interpolation syntax.
1. Review information of Security and Compliance Center posture scopes. 
2. Add reference link about posture scopes

2021-09-24 05:14 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scopes.html.markdown
> +## Example Usage
U as u in Usage

2021-09-24 05:15 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scopes.html.markdown
> +```hcl
hcl to be as terraform

2021-09-24 05:15 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scopes.html.markdown
> +## Argument Reference
R as r in reference

2021-09-24 05:15 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scopes.html.markdown
> +## Attribute Reference
R as r in Reference

2021-09-24 05:16 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scopes.html.markdown
> +	* `description` - (Optional, String) A detailed description of the scope.
The nested argument to be in alphabetical order.

2021-09-24 05:17 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scopes.html.markdown
> +	  * Constraints: Allowable values are: ibm, aws, azure, on_premise, hosted, services, openstack, gcp
1. Is constraints part of environment_type, if yes we need nested scheme....
2. Allowable values are: ibm, aws, azure, on_premise, hosted, services, openstack, gcp. as
Supported values are **ibm**, **aws**,..... in bold

2021-09-24 05:18 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scopes.html.markdown
> +	  * Constraints: Allowable values are: discovery, validation, fact_collection, fact_validation, inventory, remediation, abort_tasks, evidence, script
Is constraints part of last_scan_type, if yes we need nested scheme....
Allowable values are: discovery, validation, fact_collection, fact_validation, inventory, remediation, abort_tasks, evidence,. as
Supported values are **discovery**..... in bold

2021-09-24 05:19 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scopes.html.markdown
> +		  * Constraints: Allowable values are: pending, discovery_started, discovery_completed, error_in_discovery, gateway_aborted, controller_aborted, not_accepted, waiting_for_refine, validation_started
Is constraints part of status, if yes we need nested scheme....
Allowable values are: pending, discovery_started, discovery_completed, as
Supported values are **pending**..... in bold

2021-09-24 05:20 UTC, geethasathyamurthy reviewed
Reviewed docs comments from website/docs/.... related files

2021-09-24 18:53 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_latest_scans.html.markdown
> +Review information about the security and compliance center posture latest scans. For more information, about latest scans, see https://test.cloud.ibm.com/docs/security-compliance?topic=security-comp
Review information about the security and compliance center posture latest scans. For more information, about latest scans, see https://test.cloud.ibm.com/docs/security-compliance?topic=security-compliance-results.
as 
Review information about the security and compliance center posture latest scans. For more information, about the latest scans, see [viewing evaluation results](https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-results).

Note: please do provide the hyperlink using []() syntax, and should not provide stage docs link for the registry docs.

2021-09-24 18:54 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_profiles.html.markdown
> +Review information about the security and compliance center posture latest scans. For more information, about profiles see https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-pro
please do provide the hyperlink using []() syntax as shown in above, and should not provide stage docs link for the registry docs.

2021-09-24 18:54 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scan_summaries.html.markdown
> +Review information of Security and Compliance Center scan summaries.
please do provide the hyperlink using []() syntax as shown in above, and should not provide stage docs link for the registry docs.

2021-09-24 18:56 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scan_summaries.html.markdown
> +
can remove the additional empty lines.

2021-09-24 18:58 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scan_summaries.html.markdown
> +		* Supported values are **pending**, **discovery_started**, **discovery_completed**, **error_in_discovery**, **gateway_aborted**, **controller_aborted**, **not_accepted**, **waiting_for_refine**, **
Recheck this statement, as we are not seeing the bold string as we see in line 67.

2021-09-24 19:00 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scans_summary.html.markdown
> +Review information of Security and Compliance Center posture scan summary.
1. The hyperlink should be provided with []() syntax, as shown in the first comment. 
2. Delete test. in the https://test.cloud.ibm.com..... link

2021-09-24 19:01 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scans_summary.html.markdown
> +
additional empty lines can be deleted.

2021-09-24 19:03 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scopes.html.markdown
> +Review information of Security and Compliance Center posture scopes see.
This sentence should be reworded as per the first comment provided. 

For more information, about security compliance scope, see [Managing scopes](https://cloud.ibm.com/docs/security-compliance?topic=security-compliance-scopes)

2021-09-24 19:04 UTC, geethasathyamurthy commented on website/docs/d/scc_posture_scopes.html.markdown
> +		  * Constraints: Supported values are: **pending**, **discovery_started**, **discovery_completed**, **error_in_discovery**, **gateway_aborted**, **controller_aborted**, **not_accepted**, **waiting_
please do check why the strings are not displayed in bold after using **asdf**

2021-09-24 19:04 UTC, geethasathyamurthy reviewed
Few comments to be incorporated.

2021-09-27 10:09 UTC, merged