user-agent update for VPC
IBM-Cloud/terraform-provider-ibm pull request #3162
Opened 2021-09-30 14:12 UTC by SunithaGudisagarIBM

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000
https://jiracloud.swg.usma.ibm.com:8443/browse/UI-18867

Output from acceptance testing:

```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISVPC_basic'

```
<img width="677" alt="Screenshot 2021-09-30 at 4 23 14 PM" src="https://user-images.githubusercontent.com/78336632/135471682-154e357e-ee20-43d7-b223-f8edd82d4f17.png">

2021-09-30 14:22 UTC, SunithaGudisagarIBM commented
@VaishnaviGopal Can you please review this PR

2021-09-30 14:43 UTC, VaishnaviGopal requested changes

2021-09-30 14:43 UTC, VaishnaviGopal commented on ibm/config.go
> +		vpcclient.Service.EnableRetries(c.RetryCount, c.RetryDelay)
this is called twice in the code 
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/1756c6e10323b31f698efd7d597b26821d37ab01/ibm/config.go#L1389
 https://github.com/IBM-Cloud/terraform-provider-ibm/blob/1756c6e10323b31f698efd7d597b26821d37ab01/ibm/config.go#L1398
 
 Make sure it is called at one place

2021-11-09 11:22 UTC, kavya498 commented
Closing this PR as it is taken care in https://github.com/IBM-Cloud/terraform-provider-ibm/commit/b041104178d7fdc10b21203cd5ddb06dba3580b7

2021-11-09 11:22 UTC, closed without merging