Added new resource attribute service_type for access policies
IBM-Cloud/terraform-provider-ibm pull request #3347
Opened 2021-11-19 08:56 UTC by Rajesh-Pirati

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #3192 

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2021-11-22 13:52 UTC, swcolley commented on website/docs/r/iam_service_policy.html.markdown
> +		service_type = "service"
Should this be formatted the same as other md files?

2021-11-22 13:54 UTC, swcolley requested changes
Terraform Changes and tests look good. I left one comment about a md file.

2021-11-29 14:02 UTC, swcolley approved these changes
Looks good to me.

2021-11-30 18:43 UTC, kavya498 approved these changes

2021-12-01 11:21 UTC, hkantare approved these changes

2021-12-01 11:22 UTC, merged