Update name parameter for DHCP service create
IBM-Cloud/terraform-provider-ibm pull request #3859
Opened 2022-06-20 17:08 UTC by guruhosmath

Update name parameter for DHCP service create

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #[6208](https://jsw.ibm.com/browse/POWERIAAS-6208)

Output from acceptance testing:
```
$ make testacc TESTARGS='-run=TestAccIBMPIDhcpWithDhcpServerName'
PASS: TestAccIBMPIDhcpWithDhcpServerName (428.55s)
PASS
```

2022-06-25 16:19 UTC, yussufsh requested changes

2022-06-25 16:19 UTC, yussufsh commented on website/docs/r/pi_dhcp.html.markdown
> +- `pi_dhcp_server_name` - (Optional, String) Name of the dhcp server.
```suggestion
- `pi_dhcp_server_name` - (Optional, String) Name of the DHCP service.
```

2022-06-25 16:19 UTC, yussufsh commented on website/docs/r/pi_dhcp.html.markdown
> +- `pi_dhcp_dns_server` - (Optional, String) IP address of dns server for dhcp server.
```suggestion
- `pi_dhcp_dns_server` - (Optional, String) DNS Server for DHCP service.
```

2022-06-25 16:19 UTC, yussufsh commented on go.mod
> +replace github.com/IBM-Cloud/power-go-client => github.com/guruhosmath/power-go-client v1.0.84
You will need latest commit hash or tag.

2022-08-05 17:45 UTC, yussufsh commented
@guruhosmath any updates?

2022-08-10 10:57 UTC, guruhosmath commented
Changes went in as part of https://github.com/IBM-Cloud/terraform-provider-ibm/pull/3916 . So closing this PR.

2022-08-10 10:57 UTC, closed without merging