Fix GRE tunnel in cloud connection
IBM-Cloud/terraform-provider-ibm pull request #4093
Opened 2022-10-07 12:59 UTC by dhirendersingh19

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2022-10-07 20:22 UTC, rmoralesjr requested changes
I believe Harini will want to see the results of the test cases from ibm/service/power/resource_ibm_pi_cloud_connection_test.go
pasted in the comments. Thanks.

2022-10-10 06:40 UTC, kavya498 approved these changes

2022-10-11 04:50 UTC, hkantare commented
@dhirendersingh19 Can you please add testcase results

2022-10-17 11:10 UTC, merged

2022-10-21 07:08 UTC, rmoralesjr reviewed
LGTM