DNM Support for AddOn parameters
IBM-Cloud/terraform-provider-ibm pull request #4408
Opened 2023-03-15 07:35 UTC by aayushsss1

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2023-03-15 13:14 UTC, hasan4791 requested changes

2023-03-15 13:14 UTC, hasan4791 commented on ibm/service/kubernetes/resource_ibm_container_addons.go
> +func validateAddonOptions(jsonInput map[string]interface{}, yamlDefault map[string]interface{}) (bool, error) {
pass the inputs as pointers.

2023-03-15 13:14 UTC, hasan4791 commented on ibm/service/kubernetes/resource_ibm_container_addons.go
> +func updateAddOnOptions(jsonInput map[string]interface{}, yamlDefault map[string]interface{}) map[string]interface{} {
pass the inputs as pointers & we can remove the return statement from this function.

2023-03-15 13:14 UTC, hasan4791 commented on website/docs/d/container_addons.html.markdown
>  ## Attribute reference
Add "options" parameter also.

2023-03-16 05:04 UTC, aayushsss1 commented on ibm/service/kubernetes/resource_ibm_container_addons.go
> -							rmParam.Version = newPack["version"].(string)
Yeah, I was going through the code and uncovered it

2023-03-16 05:12 UTC, aayushsss1 commented on ibm/service/kubernetes/resource_ibm_container_addons.go
> +	// Check if parameters are given in terraform, if no, then return
csClient, err := meta.(conns.ClientSession).ContainerAPI(), is above this line, so I've defined this just below

2023-03-16 05:30 UTC, aayushsss1 commented on ibm/service/kubernetes/resource_ibm_container_addons.go
> +							ForceNew:    false,
Which parameter? ForceNew in options?

2023-03-20 10:48 UTC, akgunjal reviewed
common comments are given here:

1. The folder structure should be `examples/openshift-data-foundation/addon/main.tf`
2. Change the `AddOn` folder to `ibm_odf_addon`
3. Change the `CRD` folder to `ocscluster`
4. Also change shell script file names to all lowercase

2023-03-20 10:48 UTC, akgunjal commented on examples/openshift-data-foundation/deployment/README.md
> +# Deploying and Managing Openshift Data Foundation (Test)
change the title to 
```
[Tech Preview] Deploying and Managing Openshift Data Foundation
```

2023-03-20 10:48 UTC, akgunjal commented on examples/openshift-data-foundation/deployment/README.md
> +This example shows how to Deploy and Manage your Openshift Data Foundation add-on on a Red Hat Openshift Cluster. Note this template is still in development, so please be advised before using in prod
Change this line as 
```
This example shows how to deploy and manage the Openshift Data Foundation (ODF) on IBM Cloud VPC based RedHat Openshift cluster.
```

2023-03-20 10:48 UTC, akgunjal commented on examples/openshift-data-foundation/deployment/README.md
> +This sample configuration will deploy the add-on, scale and upgrade it using the "ibm_container_addons" and kubernetes_manifest from the ibm terraform provider and kubernetes provider respectively.
change this line 
```
This sample configuration will deploy the add-on
```
as below
```
This sample configuration will deploy the ODF
```

2023-03-20 10:48 UTC, akgunjal commented on examples/openshift-data-foundation/deployment/README.md
> +The following use cases are handled by editing the input.tfvars file. Terraform resources need to be touched.
Remove the line `Terraform resources need to be touched.`

2023-03-20 10:48 UTC, akgunjal commented on examples/openshift-data-foundation/deployment/README.md
> +odfVersion = "4.10.0"
Change default odfVersion to `4.12`

2023-03-20 10:48 UTC, akgunjal commented on examples/openshift-data-foundation/deployment/README.md
> +### Create & Deployment:
Change this to `ODF deployment`

2023-03-20 10:48 UTC, akgunjal commented on examples/openshift-data-foundation/deployment/README.md
> +### Editing the Ocscluster custom resource
change this to `ODF scale-up`

2023-03-20 10:48 UTC, akgunjal commented on examples/openshift-data-foundation/deployment/README.md
> +```hcl
Remove `hcl` if not needed

2023-03-20 10:48 UTC, akgunjal commented on examples/openshift-data-foundation/deployment/README.md
> +workerNodes = null -> "worker_1_ID,worker_2_ID"
change the example to 
```
workerNodes = "worker_1_ID,worker_2_ID,worker_1_ID,worker_3_ID" -> "worker_1_ID,worker_2_ID,worker_1_ID,worker_3_ID,worker_4_ID,worker_5_ID,worker_1_ID,worker_6_ID"
```
Also add a note for workerNodes that it should be updated only if workerNodes was provided as input during ODF deploy.

2023-03-20 10:48 UTC, akgunjal commented on examples/openshift-data-foundation/deployment/README.md
> +### Update
change this to `ODF upgrade`

2023-03-20 10:48 UTC, akgunjal commented on examples/openshift-data-foundation/deployment/README.md
> +```hcl
Remove `hcl`

2023-03-20 10:48 UTC, akgunjal commented on examples/openshift-data-foundation/deployment/README.md
> +workerNodes = "false" -> "true"
I think it should be `ocsUpgrade`

2023-03-20 10:48 UTC, akgunjal commented on examples/openshift-data-foundation/deployment/README.md
> +odfVersion = "4.10.0" -> "4.11.0"
change version from 4.12 to 4.13

2023-03-20 10:48 UTC, akgunjal commented on examples/openshift-data-foundation/deployment/input.tfvars
> +odfVersion = "4.10.0"
change it to 4.12.0

2023-03-21 05:13 UTC, aayushsss1 commented on examples/openshift-data-foundation/deployment/README.md
> +```hcl
configuration language, it's used to depict the terraform files in readme

2023-03-21 05:15 UTC, aayushsss1 commented on examples/openshift-data-foundation/deployment/README.md
> +* [ ODF Deployment & Management ](https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/examples/openshift-data-foundation/deployment)
The other examples were similar so I added this, I'm not sure if it's required. Will check and make the changes

2023-04-10 06:54 UTC, hasan4791 commented
@hkantare @kavya498 
Could you please take a look at this PR!!

2023-04-21 10:48 UTC, hkantare approved these changes

2023-04-21 10:49 UTC, merged