build: generate project code
IBM-Cloud/terraform-provider-ibm pull request #4447
Opened 2023-03-29 08:28 UTC by dvesperini

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2023-03-30 07:14 UTC, dvesperini commented
@handadi @hkantare 
Please review

2023-03-30 17:36 UTC, kavya498 requested changes
Kindly, resolve conflicts and attach testcase results of resource and datasources to the PR.

2023-03-30 17:36 UTC, kavya498 commented on ibm/service/project/resource_ibm_project.go
> +	if hasChange {
It is never going to enter this loop.
kindly check for update on arguments before this if condition

Ref: https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/service/vpc/resource_ibm_is_vpc.go#L831

2023-03-30 17:36 UTC, kavya498 commented on ibm/service/project/resource_ibm_project.go
> +
We would encourage you to provide `destroy` flag feature like in api.
Is there any specific reason for not including it?

2023-03-30 17:36 UTC, kavya498 commented on website/docs/r/project.html.markdown
> +		id = "id"
Correct me if I'm wrong here. 
id here is project id? If so how do we provide project id during creation of project.

2023-03-30 17:36 UTC, kavya498 commented on website/docs/r/project.html.markdown
> +		locator_id = "locator_id"
kindly provide working example
kkindly provide valid values to the argument to make this doc more user friendly.

2023-03-30 17:36 UTC, kavya498 commented on website/docs/r/project.html.markdown
> +
You can remove 
`# Provider Configuration`
`### Static credentials`
`### Environment variables` sections from all project docs as it is generic doc and is available in provider page - https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs#authentication

2023-03-30 17:36 UTC, kavya498 commented on ibm/service/project/data_source_ibm_event_notification.go
> +
topic_names is not been set

2023-03-30 17:36 UTC, kavya498 commented on ibm/service/project/data_source_ibm_event_notification_test.go
> +			id = "id"
Kindly provide working example to the testcase.

2023-03-30 20:37 UTC, dvesperini commented on go.mod
> +	github.com/damianovesperini/platform-services-go-sdk v1.0.9
cause we don't have our go sdk published under IBM

2023-03-30 20:39 UTC, dvesperini commented on ibm/service/project/data_source_ibm_event_notification.go
> +			"id": &schema.Schema{
We won't change that id into project_id, we have this naming convention also for CLI and SDK.

2023-03-30 21:12 UTC, dvesperini commented on website/docs/d/project.html.markdown
> +* `id` - (Required, Forces new resource, String) The ID of the project, which uniquely identifies it.
same as I said in the previous comment.. we want to stay with id

2023-03-31 07:59 UTC, dvesperini commented on ibm/service/project/data_source_ibm_event_notification.go
> +			"id": &schema.Schema{
We won't change this.. we have the same approach under SKD,CLI ecc..

2023-04-03 08:55 UTC, riccardo-angelilli commented on ibm/conns/config.go
> +
done

2023-04-03 10:12 UTC, riccardo-angelilli commented on ibm/conns/config.go
> +	session.projectClient, err = projectv1.NewProjectV1(projectClientOptions)
done

2023-04-06 09:58 UTC, closed without merging

2023-04-06 10:26 UTC, dvesperini commented
I'm going to close this because I have opened a new one:
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/4484