Documentation for Openshift-Data-Foundation Add-on & VPC Worker Replace
IBM-Cloud/terraform-provider-ibm pull request #4627
Opened 2023-06-16 10:14 UTC by aayushsss1

Examples Terraform Templates for ODF add-on and worker replace

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2023-06-17 13:06 UTC, hasan4791 requested changes

2023-06-18 03:14 UTC, aayushsss1 commented on examples/openshift-data-foundation/addon/ocscluster/main.tf
>        source = "IBM-Cloud/ibm"
updated version

2023-06-18 03:14 UTC, aayushsss1 commented on examples/openshift-data-foundation/vpc-worker-replace/variables.tf
> +variable "ptx_timeout" {
removed

2023-06-18 08:30 UTC, hasan4791 approved these changes

2023-06-18 08:31 UTC, hasan4791 commented
@hkantare PTAL

2023-06-19 07:45 UTC, hkantare approved these changes

2023-06-19 07:45 UTC, merged