Feat: ReplicationEnabledField for Storage Pool
IBM-Cloud/terraform-provider-ibm pull request #4791
Opened 2023-09-11 06:19 UTC by lalitpaliwal-ibm2

With this PR, user will be able to see if storage pool is replication enabled or not while accessing storage pool/pools capacity APIs.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2023-09-11 16:14 UTC, yussufsh requested changes

2023-09-11 16:14 UTC, yussufsh commented on go.mod
> +	github.com/IBM-Cloud/power-go-client v1.3.1-0.20230811154219-1b70021e9f3f
Any issue using the stable version?

2023-09-11 16:14 UTC, yussufsh commented on website/docs/d/pi_storage_pools_capacity.markdown
> +  - `replication_enabled` - (Boolean) "Replication status of the storage pool"
Remove quotes and add a full stop.

2023-09-15 09:08 UTC, lalitpaliwal-ibm2 commented
Closing the current PR, raised a separate PR including all the changes and feedback : https://github.com/powervs-ibm/terraform-provider-ibm/pull/6

2023-09-15 09:08 UTC, closed without merging