Update Power Workspace/s and Datacenter/s  DataSource Documentation
IBM-Cloud/terraform-provider-ibm pull request #4904
Opened 2023-11-06 22:02 UTC by michaelkad

- Update doc for get and getall workspace and datacenter

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2023-11-21 00:02 UTC, michaelkad commented
@hkantare @yussufsh  Could you help with reviewing this PR please?

2023-11-21 05:28 UTC, yussufsh commented
> @hkantare @yussufsh Could you help with reviewing this PR please?

There are some pending comments above.

2023-11-21 13:32 UTC, michaelkad commented
@yussufsh I do not think there has been any comments on this PR. If you were in the middle of one, please do resubmit.

2023-11-21 13:36 UTC, yussufsh requested changes

2023-11-21 13:36 UTC, yussufsh commented
> @yussufsh I do not think there has been any comments on this PR. If you were in the middle of one, please do resubmit.

You are right.. Sorry :-(

2023-11-21 13:46 UTC, michaelkad commented on website/docs/d/pi_datacenter.html.markdown
> +- `pi_datacenter_status` - (String) The Datacenter status, `active`,`maintenance` or `down`.
You are right,  I will update the go.mod 
They are the same however, they were updated to lowercase. 
https://github.com/powervs-ibm/power-go-client/blob/782d50a27da76f31d0cc1c88cf2c6a63c9f885fa/power/models/datacenter.go#L36

2023-11-21 13:46 UTC, michaelkad commented on website/docs/d/pi_datacenters.html.markdown
> +  - `pi_datacenter_type` - (String) The Datacenter type, `off-premises` or `on-premises`.
You are right,  I will update the go.mod

2023-11-21 13:48 UTC, michaelkad commented
> > @yussufsh I do not think there has been any comments on this PR. If you were in the middle of one, please do resubmit.
> 
> You are right.. Sorry :-(

You are good.  I will update go.mod

2023-11-21 14:10 UTC, yussufsh approved these changes
lgtm
@hkantare please help merge this one.

2023-11-22 07:37 UTC, hkantare commented
fix the conflicts

2023-11-22 13:31 UTC, michaelkad commented
> fix the conflicts

@hkantare The conflict has been resolved.

2023-11-23 14:03 UTC, merged