Add workspace create workspace delete resource to terraform provider
IBM-Cloud/terraform-provider-ibm pull request #4935
Opened 2023-11-20 15:05 UTC by ismirlia

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2023-11-21 00:03 UTC, michaelkad commented
@hkantare @yussufsh  Could you help with reviewing this PR please?

2023-11-21 14:44 UTC, yussufsh requested changes

2023-11-21 14:44 UTC, yussufsh commented on website/docs/r/pi_workspace.html.markdown
> +- `id` - (String) Workspace ID.
`id` should go in `Attribute reference` section.

2023-11-21 15:06 UTC, ismirlia commented on ibm/service/power/resource_ibm_pi_workspace.go
> +				ForceNew:    true,
Please mark it as a future enhancement. I am currently out and will be out until next Tuesday.

2023-11-21 15:09 UTC, yussufsh approved these changes
lgtm
@hkantare please help with this one as well.

2023-11-22 07:30 UTC, hkantare commented
Can you resolve conflits

2023-11-22 14:34 UTC, michaelkad commented
> Can you resolve conflits

@hkantare resolved.

2023-11-23 09:30 UTC, merged