Refactor public-network-pvm-instance-snapshot data source and documentation
IBM-Cloud/terraform-provider-ibm pull request #5100
Opened 2024-02-01 06:56 UTC by Diptipowervs

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-02-02 13:41 UTC, yussufsh requested changes

2024-02-02 13:41 UTC, yussufsh commented on website/docs/d/pi_public_network.html.markdown
> +Retrieve the details about a public network that is used for your Power Systems Virtual Server instance. For more information, about public network in IBM power virtual server, see [adding or removin
```suggestion
Retrieve the details about a public network that is used for your Power Systems Virtual Server instance. For more information, about public network in IBM Power Systems Virtual Server, see [adding or removing a public network
```

2024-02-05 09:22 UTC, yussufsh approved these changes
lgtm

2024-02-05 18:14 UTC, Diptipowervs commented
Test Result:-
--- PASS: TestAccIBMPINetworkDataSource_basic (27.97s)
PASS

2024-02-06 13:04 UTC, merged