GO RC SDK v2 migration
IBM-Cloud/terraform-provider-ibm pull request #5214
Opened 2024-03-19 22:09 UTC by IBM-diksha

Test cases :

--- PASS: TestAccIBMCosBucket_Basic (154.25s)

--- PASS: TestAccIBMCosBucket_Basic_Single_Site_Location (81.07s)
PASS
ok 	[github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](http://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos)	243.946s

-- PASS: TestAccIBMCosBucket_AllowedIP (116.93s)
PASS
ok 	[github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](http://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos)	122.044s

--- PASS: TestAccIBMCosBucket_ActivityTracker_Monitor (120.16s)
PASS
ok 	[github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](http://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos)	123.591s

2024-03-20 08:06 UTC, avinash1IBM requested changes

2024-03-20 08:06 UTC, avinash1IBM commented on ibm/service/cos/resource_ibm_cos_bucket.go
> +		firewall := &rcsdk.Firewall{}
Instead of rcsdk, can we change the variable name here to resourceConfiguration or similar at all the places

2024-03-20 08:57 UTC, avinash1IBM approved these changes

2024-03-21 13:39 UTC, hkantare commented on ibm/service/cos/data_source_ibm_cos_bucket.go
> +	authenticator := new(core.IamAuthenticator)
Why are we intializing authenticator here. It should be in config.go similar to CosConfigV1API()
Every time only APIkey is n't  used to work with provider. 
The provider can work with IAM tokens (in Schematics)

2024-03-21 14:45 UTC, IBM-diksha commented
Latest test cases :
--- PASS: TestAccIBMCosBucket_Basic_Single_Site_Location (109.80s)
PASS
ok 	[github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](http://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos)	286.347s
--- PASS: TestAccIBMCosBucket_Basic (169.83s)
--- PASS: TestAccIBMCosBucket_AllowedIP (181.22s)
PASS
ok 	[github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](http://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos)	187.944s
--- PASS: TestAccIBMCosBucket_ActivityTracker_Monitor (189.45s)
PASS
ok 	[github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](http://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos)	196.427s

--- PASS: TestAccIBMCOSBucketDataSource_basic (65.55s)
PASS
ok 	[github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](http://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos)	68.543s

2024-03-21 14:57 UTC, avinash1IBM approved these changes

2024-03-22 04:16 UTC, merged