Ibm pi networks data source
IBM-Cloud/terraform-provider-ibm pull request #5237
Opened 2024-03-25 16:11 UTC by ismirlia

This PR adds a ibm_pi_networks data source to read all networks in your workspace.

Solves issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5130

Looks like:
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

example = {
  "id" = "55189958-c2a8-b3b1-fd4b-468614709c1c"
  "networks" = tolist([
    {
      "access_config" = ""
      "dhcp_managed" = false
      "href" = "/pcloud/v1/cloud-instances/96a803ede12f488887588dd7a74d040f/networks/09e8a8e9-9722-4734-a95f-baef03e97d06"
      "mtu" = 0
      "name" = "test--"
      "network_id" = "09e8a8e9-9722-4734-a95f-baef03e97d06"
      "type" = "vlan"
      "vlan_id" = 725
    },
    {
      "access_config" = ""
      "dhcp_managed" = false
      "href" = "/pcloud/v1/cloud-instances/96a803ede12f488887588dd7a74d040f/networks/14b433c7-02c8-4462-b13f-8f752594f824"
      "mtu" = 0
      "name" = "bleh"
      "network_id" = "14b433c7-02c8-4462-b13f-8f752594f824"
      "type" = "vlan"
      "vlan_id" = 356
    },
    {
      "access_config" = ""
      "dhcp_managed" = false
      "href" = "/pcloud/v1/cloud-instances/96a803ede12f488887588dd7a74d040f/networks/f9d7af9b-d8bf-4e19-8dc6-6233f72f85c7"
      "mtu" = 0
      "name" = "bhagya-network"
      "network_id" = "f9d7af9b-d8bf-4e19-8dc6-6233f72f85c7"
      "type" = "vlan"
      "vlan_id" = 295
    },
  ])
  "pi_cloud_instance_id" = "7c107dc5-4b97-46af-a8b7-32c1aeabfb73"
}
```

Acceptance test:
```
--- PASS: TestAccIBMPINetworksDataSource_basic (13.61s)
PASS
```

2024-03-26 15:51 UTC, michaelkad approved these changes

2024-03-29 15:13 UTC, yussufsh requested changes

2024-03-29 15:13 UTC, yussufsh commented on ibm/service/power/data_source_ibm_pi_networks.go
> +// Copyright IBM Corp. 2017, 2021 All Rights Reserved.
```suggestion
// Copyright IBM Corp. 2024 All Rights Reserved.
```

2024-03-29 15:13 UTC, yussufsh commented on ibm/service/power/data_source_ibm_pi_networks_test.go
> +// Copyright IBM Corp. 2017, 2021 All Rights Reserved.
```suggestion
// Copyright IBM Corp. 2024 All Rights Reserved.
```

2024-03-29 16:39 UTC, ismirlia commented on ibm/service/power/data_source_ibm_pi_networks_test.go
> +// Copyright IBM Corp. 2017, 2021 All Rights Reserved.
made changes

2024-03-29 16:39 UTC, ismirlia commented on ibm/service/power/data_source_ibm_pi_networks.go
> +// Copyright IBM Corp. 2017, 2021 All Rights Reserved.
made changes

2024-03-29 16:43 UTC, yussufsh approved these changes
lgtm

2024-03-30 04:25 UTC, hkantare commented
Fix conflicts in PR

2024-04-01 14:51 UTC, ismirlia commented
@hkantare I have fixed the conflicts.

2024-04-24 04:54 UTC, merged