Revert type change in the instance list
IBM-Cloud/terraform-provider-ibm pull request #5260
Opened 2024-04-03 18:45 UTC by ismirlia

This PR undoes a type change from set to list due to compatibility reasons.

2024-04-03 18:54 UTC, michaelkad requested changes
Could you update this as well?
back to ->`pvmNetworks := expandPVMNetworks(d.Get(PIInstanceNetwork).([]interface{}))` rather than set

2024-04-04 13:59 UTC, michaelkad approved these changes

2024-04-04 14:00 UTC, michaelkad commented
@hkantare  would you  please help review this pr?

2024-04-08 17:54 UTC, ismirlia commented
@hkantare the change from a list to a set changed some semantics about which networks get attached in which order, which is a problem for the test team.

2024-04-12 10:23 UTC, hkantare approved these changes

2024-04-12 10:23 UTC, merged