Add KMIP Management API support to KMS service.
IBM-Cloud/terraform-provider-ibm pull request #5322
Opened 2024-05-01 16:08 UTC by MDarmawan

Reference Issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5299

I also laid the groundwork for adding sweepers to clean up after KMS test resources by adding a prefix to the instances created by the tests.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

<details>

<summary>Test Results</summary>

```
$ make testacc TESTARGS='-run=TestAccXXX'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./ibm/service/kms -v -run=TestAccIBMKMS -timeout 700m
=== RUN   TestAccIBMKMSDataSourceKeyPolicy_basicNew
--- PASS: TestAccIBMKMSDataSourceKeyPolicy_basicNew (44.40s)
=== RUN   TestAccIBMKMSKeyRingDataSource_basic
--- PASS: TestAccIBMKMSKeyRingDataSource_basic (39.41s)
=== RUN   TestAccIBMKMSKeyDataSource_basic
--- PASS: TestAccIBMKMSKeyDataSource_basic (40.83s)
=== RUN   TestAccIBMKMSKeyDataSource_description
--- PASS: TestAccIBMKMSKeyDataSource_description (39.53s)
=== RUN   TestAccIBMKMSKeyDataSource_Key
--- PASS: TestAccIBMKMSKeyDataSource_Key (45.16s)
=== RUN   TestAccIBMKMSKeyDataSourceHPCS_basic
    data_source_ibm_kms_key_test.go:77: 
--- SKIP: TestAccIBMKMSKeyDataSourceHPCS_basic (0.00s)
=== RUN   TestAccIBMKMSDataSource_basic
--- PASS: TestAccIBMKMSDataSource_basic (42.73s)
=== RUN   TestAccIBMKMSHPCSDataSource_basic
    data_source_ibm_kms_keys_test.go:36: 
--- SKIP: TestAccIBMKMSHPCSDataSource_basic (0.00s)
=== RUN   TestAccIBMKMSKeyDataSource_Keys
--- PASS: TestAccIBMKMSKeyDataSource_Keys (53.06s)
=== RUN   TestAccIBMKMSKMIPAdapterDataSource_basic
--- PASS: TestAccIBMKMSKMIPAdapterDataSource_basic (59.12s)
=== RUN   TestAccIBMKMSKMIPAdaptersDataSource_basic
--- PASS: TestAccIBMKMSKMIPAdaptersDataSource_basic (50.49s)
=== RUN   TestAccIBMKMSKMIPClientCertDataSource_basic
--- PASS: TestAccIBMKMSKMIPClientCertDataSource_basic (60.59s)
=== RUN   TestAccIBMKMSKMIPClientCertsDataSource_basic
--- PASS: TestAccIBMKMSKMIPClientCertsDataSource_basic (57.14s)
=== RUN   TestAccIBMKMSKMIPObjectDataSource_basic
--- PASS: TestAccIBMKMSKMIPObjectDataSource_basic (32.11s)
=== RUN   TestAccIBMKMSKMIPObjectsDataSource_basic
--- PASS: TestAccIBMKMSKMIPObjectsDataSource_basic (55.90s)
=== RUN   TestAccIBMKMSInstancePolicy_basic_check
--- PASS: TestAccIBMKMSInstancePolicy_basic_check (45.57s)
=== RUN   TestAccIBMKMSInstancePolicy_rotation_check
--- PASS: TestAccIBMKMSInstancePolicy_rotation_check (34.80s)
=== RUN   TestAccIBMKMSInstancePolicy_dualAuth_check
--- PASS: TestAccIBMKMSInstancePolicy_dualAuth_check (34.28s)
=== RUN   TestAccIBMKMSInstancePolicy_metrics_check
--- PASS: TestAccIBMKMSInstancePolicy_metrics_check (35.56s)
=== RUN   TestAccIBMKMSInstancePolicy_kcia_check
--- PASS: TestAccIBMKMSInstancePolicy_kcia_check (41.02s)
=== RUN   TestAccIBMKMSInstancePolicy_kcia_attributes_check
--- PASS: TestAccIBMKMSInstancePolicy_kcia_attributes_check (41.19s)
=== RUN   TestAccIBMKMSInstancePolicyWithKey
--- PASS: TestAccIBMKMSInstancePolicyWithKey (41.28s)
=== RUN   TestAccIBMKMSInstancePolicy_invalid_interval_check
--- PASS: TestAccIBMKMSInstancePolicy_invalid_interval_check (0.36s)
=== RUN   TestAccIBMKMSResource_Key_Alias_Name
--- PASS: TestAccIBMKMSResource_Key_Alias_Name (55.85s)
=== RUN   TestAccIBMKMSResource_Key_Alias_Duplicate
--- PASS: TestAccIBMKMSResource_Key_Alias_Duplicate (36.97s)
=== RUN   TestAccIBMKMSResource_Key_Alias_Key_Check
--- PASS: TestAccIBMKMSResource_Key_Alias_Key_Check (71.07s)
=== RUN   TestAccIBMKMSResource_Key_Alias_Key_Limit
    resource_ibm_kms_key_alias_test.go:139: Step 1/1, expected an error but got none
--- FAIL: TestAccIBMKMSResource_Key_Alias_Key_Limit (38.71s)
=== RUN   TestAccIBMKMSKeyPolicy_basic_check
--- PASS: TestAccIBMKMSKeyPolicy_basic_check (52.69s)
=== RUN   TestAccIBMKMSKeyPolicy_basic_check_enable
--- PASS: TestAccIBMKMSKeyPolicy_basic_check_enable (76.11s)
=== RUN   TestAccIBMKMSKeyPolicy_rotation_check
--- PASS: TestAccIBMKMSKeyPolicy_rotation_check (41.53s)
=== RUN   TestAccIBMKMSKeyPolicy_dualAuth_check
--- PASS: TestAccIBMKMSKeyPolicy_dualAuth_check (39.78s)
=== RUN   TestAccIBMKMSKeyPolicy_dualAuth_check_with_Alias
--- PASS: TestAccIBMKMSKeyPolicy_dualAuth_check_with_Alias (42.35s)
=== RUN   TestAccIBMKMSResource_Key_Ring_Name
--- PASS: TestAccIBMKMSResource_Key_Ring_Name (35.47s)
=== RUN   TestAccIBMKMSResource_Key_Ring_Key
--- PASS: TestAccIBMKMSResource_Key_Ring_Key (49.18s)
=== RUN   TestAccIBMKMSResource_Key_Ring_Not_Exist
--- PASS: TestAccIBMKMSResource_Key_Ring_Not_Exist (29.81s)
=== RUN   TestAccIBMKMSResource_Key_Ring_ForceDeleteFalse
    resource_ibm_kms_key_rings_test.go:78: Step 2/4, expected an error with pattern, no match on: Error running post-apply plan: exit status 1
        
        Error: [ERROR] No keys in instance 2e130cba-8916-4b41-9b73-e03bf8e1e56e
        
          with data.ibm_kms_keys.test_keys,
          on terraform_plugin_test.tf line 10, in data "ibm_kms_keys" "test_keys":
          10: 		data "ibm_kms_keys" "test_keys" {
        
        ---
        id: terraform-3493d491
        summary: '[ERROR] No keys in instance 2e130cba-8916-4b41-9b73-e03bf8e1e56e'
        severity: error
        resource: (Data) ibm_kms_keys
        operation: read
        component:
          name: github.com/IBM-Cloud/terraform-provider-ibm
          version: 1.65.0-beta0
        ---
        
--- FAIL: TestAccIBMKMSResource_Key_Ring_ForceDeleteFalse (51.39s)
=== RUN   TestAccIBMKMSResource_Key_Ring_ForceDeleteTrue
--- PASS: TestAccIBMKMSResource_Key_Ring_ForceDeleteTrue (63.38s)
=== RUN   TestAccIBMKMSResource_Key_Ring_ForceDeleteTrueContainsActiveKeys
    resource_ibm_kms_key_rings_test.go:156: Step 2/4, expected an error but got none
--- FAIL: TestAccIBMKMSResource_Key_Ring_ForceDeleteTrueContainsActiveKeys (52.32s)
=== RUN   TestAccIBMKMSResource_basic
    resource_ibm_kms_key_test.go:29: Step 5/6 error: Error running apply: exit status 1
        
        Error: [ERROR] Error when creating resource instance: This plan requires a paid account. You can upgrade by adding a credit card to your account or you can select the free plan if it's available. with resp code: {
            "StatusCode": 400,
            "Headers": {
                "Cache-Control": [
                    "max-age=0, no-cache, no-store"
                ],
                "Content-Length": [
                    "214"
                ],
                "Content-Type": [
                    "application/json; charset=utf-8"
                ],
                "Date": [
                    "Wed, 01 May 2024 17:33:42 GMT"
                ],
                "Expires": [
                    "Wed, 01 May 2024 17:33:42 GMT"
                ],
                "Pragma": [
                    "no-cache"
                ],
                "Request-Id": [
                    "bss-0e6dabba12b2f425"
                ],
                "Retry-After": [
                    "0"
                ],
                "Server": [
                    "istio-envoy"
                ],
                "Set-Cookie": [
                    "ak_bmsc=5CF0716C272544142F530F8456288873~000000000000000000000000000000~YAAQEGbNF4C6bPKOAQAAGCE4NReBZA3pikQxdPSgL2T5iwzYfD8lTbcqGz4KiAdknLN04HuKKlR2oBqv7zlOik8DC4VvQPkJ2HzpW0ACRUsmWVVDHUmpwyAxiKbqjikhg2CXR3phUbOud6Uojb8QhoxQ1CBIGj8ZxFtWJgtk4YTR7/qwVsOWx0wdAgPxxINjm0/tWZAZbnOKghzF81/CsgyJ52xE29moFY+VZ8grTOya0bZUTkUgSdjbKlyVLCFpuQ2SwiiYBRrAeA5DDQAyRlY1yvTsk2sWWYiBbsgK/bEPq/vFJr1rAt4hNqJUuuW5OCH53jWhKbY/iPqh4L0hWNE/5trjPHXAgsPhXkHNsSATCq25NxGeAgCtCbnM/O+M8dTMmlN2xQ/uQE0=; Domain=.cloud.ibm.com; Path=/; Expires=Wed, 01 May 2024 1 [...]

2024-05-01 18:54 UTC, william8siew requested changes
good work, small changes requested, just logging changes

2024-05-01 18:54 UTC, william8siew commented on ibm/service/kms/data_source_ibm_kms_kmip_adapter.go
> +func DataSourceIBMKMSKmipAdapter() *schema.Resource {
I do think this is a little less readable than just having those 3 attributes updated, but thats personal preference

2024-05-01 18:54 UTC, william8siew commented on ibm/service/kms/data_source_ibm_kms_kmip_client_certificate.go
> +		return fmt.Errorf("Error setting adapter_id: %s", err)
format with prefix [ERROR]

2024-05-01 18:54 UTC, william8siew commented on ibm/service/kms/data_source_ibm_kms_kmip_client_certificate.go
> +		return fmt.Errorf("Error setting adapter_name: %s", err)
format with prefix [ERROR]

2024-05-01 18:54 UTC, william8siew commented on ibm/service/kms/data_source_ibm_kms_kmip_client_certificates.go
> +		return fmt.Errorf("Error setting adapter_id: %s", err)
format with prefix [ERROR]

2024-05-01 18:54 UTC, william8siew commented on ibm/service/kms/data_source_ibm_kms_kmip_client_certificates.go
> +		return fmt.Errorf("Error setting adapter_name: %s", err)
format with prefix [ERROR]

2024-05-01 18:54 UTC, william8siew commented on ibm/service/kms/data_source_ibm_kms_kmip_object.go
> +		return fmt.Errorf("Error setting adapter_id: %s", err)
format with prefix [ERROR] in this file

2024-05-01 18:54 UTC, william8siew commented on ibm/service/kms/data_source_ibm_kms_kmip_objects.go
> +			return fmt.Errorf("Error converting object_state_filter into []any")
format with prefix [ERROR] in this file

2024-05-01 18:54 UTC, william8siew commented on ibm/service/kms/resource_ibm_kms_key.go
> +	// if len(registrations.Registrations) > 0 {
if unused please remove

2024-05-01 18:54 UTC, william8siew commented on ibm/service/kms/resource_ibm_kms_key_with_policy_overrides_test.go
> +	if ibmKMSSuppressKeyWithPolicyOverridesTests {
once you add the registrations to instance policies, remove this code for skipping

2024-05-01 18:54 UTC, william8siew commented on ibm/service/kms/resource_ibm_kms_kmip_adapter.go
> +			err = fmt.Errorf("Error converting profile data to map[string]interface{}")
[ERROR] prefix formatting please

2024-05-01 18:54 UTC, william8siew commented on ibm/service/kms/resource_ibm_kms_kmip_client_cert.go
> +			err = fmt.Errorf("Error converting name to string")
[ERROR] prefix formatting please

2024-05-01 18:59 UTC, william8siew commented on ibm/service/kms/resource_ibm_kms_kmip_adapter.go
> +		// 	Create: schema.DefaultTimeout(10 * time.Minute),
why is this commented out?

2024-05-01 19:00 UTC, william8siew commented on ibm/service/kms/resource_ibm_kms_kmip_client_cert.go
> +	// TODO: subresources
what subresources?

2024-05-01 19:05 UTC, william8siew commented
Adding this here as well, I believe we discussed a force_delete option for adapters to delete the associated kmip_objects. 
I would like to see unit tests for this scenario with the flag on(clean delete) and off(409) as it is a very critical flow of the kmip lifecycle

2024-05-01 21:49 UTC, MDarmawan commented
> Adding this here as well, I believe we discussed a force_delete option for adapters to delete the associated kmip_objects. I would like to see unit tests for this scenario with the flag on(clean delete) and off(409) as it is a very critical flow of the kmip lifecycle

Force Delete as a query param will wait for implementation. Currently we are deleting the associated KMIP objects by default in the delete KMIP adapter behavior, it will error on attempt to delete an active KMIP object, but there is no way to force that with what we have implemented.

2024-05-02 19:21 UTC, william8siew commented
> > Adding this here as well, I believe we discussed a force_delete option for adapters to delete the associated kmip_objects. I would like to see unit tests for this scenario with the flag on(clean delete) and off(409) as it is a very critical flow of the kmip lifecycle
> 
> Force Delete as a query param will wait for implementation. Currently we are deleting the associated KMIP objects by default in the delete KMIP adapter behavior, it will error on attempt to delete an active KMIP object, but there is no way to force that with what we have implemented.

Right, we will wait for force_delete. If the default attempts to delete kmip objects but fails on an active one, just make sure to test for the 409 through terraform the

2024-05-02 20:14 UTC, william8siew approved these changes

2024-05-02 20:48 UTC, MDarmawan commented
Added some more Acceptance Tests, results below:
```==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./ibm/service/kms -v -run=TestAccIBMKMSKMIP -timeout 700m
=== RUN   TestAccIBMKMSKMIPAdapterDataSource_basic
--- PASS: TestAccIBMKMSKMIPAdapterDataSource_basic (67.46s)
=== RUN   TestAccIBMKMSKMIPAdaptersDataSource_basic
--- PASS: TestAccIBMKMSKMIPAdaptersDataSource_basic (65.09s)
=== RUN   TestAccIBMKMSKMIPClientCertDataSource_basic
--- PASS: TestAccIBMKMSKMIPClientCertDataSource_basic (71.32s)
=== RUN   TestAccIBMKMSKMIPClientCertsDataSource_basic
--- PASS: TestAccIBMKMSKMIPClientCertsDataSource_basic (61.95s)
=== RUN   TestAccIBMKMSKMIPObjectDataSource_basic
--- PASS: TestAccIBMKMSKMIPObjectDataSource_basic (36.53s)
=== RUN   TestAccIBMKMSKMIPObjectsDataSource_basic
--- PASS: TestAccIBMKMSKMIPObjectsDataSource_basic (63.64s)
=== RUN   TestAccIBMKMSKMIPAdapterResource_basic
--- PASS: TestAccIBMKMSKMIPAdapterResource_basic (41.04s)
=== RUN   TestAccIBMKMSKMIPAdapterResource_InvalidCRKStandardKeyErr
--- PASS: TestAccIBMKMSKMIPAdapterResource_InvalidCRKStandardKeyErr (54.08s)
=== RUN   TestAccIBMKMSKMIPAdapterResource_DuplicateAdapterNameErr
--- PASS: TestAccIBMKMSKMIPAdapterResource_DuplicateAdapterNameErr (34.96s)
=== RUN   TestAccIBMKMSKMIPAdapterResource_CRKNotFoundErr
--- PASS: TestAccIBMKMSKMIPAdapterResource_CRKNotFoundErr (30.74s)
=== RUN   TestAccIBMKMSKMIPClientCertResource_basic
--- PASS: TestAccIBMKMSKMIPClientCertResource_basic (44.95s)
=== RUN   TestAccIBMKMSKMIPClientCertResource_DuplicateCertError
--- PASS: TestAccIBMKMSKMIPClientCertResource_DuplicateCertError (37.57s)
=== RUN   TestAccIBMKMSKMIPClientCertResource_InvalidCert
--- PASS: TestAccIBMKMSKMIPClientCertResource_InvalidCert (34.23s)
=== RUN   TestAccIBMKMSKMIPClientCertResource_DuplicateNameError
--- PASS: TestAccIBMKMSKMIPClientCertResource_DuplicateNameError (37.09s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/kms	685.026s
```

2024-05-07 15:58 UTC, MDarmawan commented
```=== RUN   TestAccIBMKMSKMIPAdapterDataSource_basic
--- PASS: TestAccIBMKMSKMIPAdapterDataSource_basic (70.65s)
=== RUN   TestAccIBMKMSKMIPAdaptersDataSource_basic
--- PASS: TestAccIBMKMSKMIPAdaptersDataSource_basic (63.42s)
=== RUN   TestAccIBMKMSKMIPClientCertDataSource_basic
--- PASS: TestAccIBMKMSKMIPClientCertDataSource_basic (60.33s)
=== RUN   TestAccIBMKMSKMIPClientCertsDataSource_basic
--- PASS: TestAccIBMKMSKMIPClientCertsDataSource_basic (60.95s)
=== RUN   TestAccIBMKMSKMIPObjectDataSource_basic
--- PASS: TestAccIBMKMSKMIPObjectDataSource_basic (32.06s)
=== RUN   TestAccIBMKMSKMIPObjectsDataSource_basic
--- PASS: TestAccIBMKMSKMIPObjectsDataSource_basic (56.57s)
=== RUN   TestAccIBMKMSKMIPAdapterResource_basic
--- PASS: TestAccIBMKMSKMIPAdapterResource_basic (37.47s)
=== RUN   TestAccIBMKMSKMIPAdapterResource_InvalidCRKStandardKeyErr
--- PASS: TestAccIBMKMSKMIPAdapterResource_InvalidCRKStandardKeyErr (39.07s)
=== RUN   TestAccIBMKMSKMIPAdapterResource_DuplicateAdapterNameErr
--- PASS: TestAccIBMKMSKMIPAdapterResource_DuplicateAdapterNameErr (31.68s)
=== RUN   TestAccIBMKMSKMIPAdapterResource_CRKNotFoundErr
--- PASS: TestAccIBMKMSKMIPAdapterResource_CRKNotFoundErr (31.21s)
=== RUN   TestAccIBMKMSKMIPClientCertResource_basic
--- PASS: TestAccIBMKMSKMIPClientCertResource_basic (43.58s)
=== RUN   TestAccIBMKMSKMIPClientCertResource_DuplicateCertError
--- PASS: TestAccIBMKMSKMIPClientCertResource_DuplicateCertError (36.65s)
=== RUN   TestAccIBMKMSKMIPClientCertResource_InvalidCert
--- PASS: TestAccIBMKMSKMIPClientCertResource_InvalidCert (32.99s)
=== RUN   TestAccIBMKMSKMIPClientCertResource_DuplicateNameError
--- PASS: TestAccIBMKMSKMIPClientCertResource_DuplicateNameError (35.82s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/kms     635.362s```
there were some changes to the provider code, so i reran the tests

2024-05-10 17:31 UTC, stephaniegalang reviewed
Review of docs only. No major blockers found

2024-05-10 17:31 UTC, stephaniegalang commented on website/docs/d/kms_kmip_adapters.html.markdown
> +  Manages key rings for IBM hs-crypto and KMS.
says key ring instead of kmip adapter

2024-05-10 17:31 UTC, stephaniegalang commented on website/docs/d/kms_kmip_adapters.html.markdown
> +page_title: "IBM : kms-kmip-adapter"
```suggestion
page_title: "IBM : kms-kmip-adapters"
```

2024-05-10 17:31 UTC, stephaniegalang commented on website/docs/d/kms_kmip_adapters.html.markdown
> +Retrieves a list of KMIP adapters from a Key Protect service instance. The region parameter in the `provider.tf` file must be set. If region parameter is not specified, `us-south` is used by default.
```suggestion
Retrieves a list of KMIP adapters from a Key Protect service instance. The region parameter in the `provider.tf` file must be set. If region parameter is not specified, `us-south` is used by default. If the region in the `provider.tf` file is different from the Key Protect instance, the instance cannot be retrieved by Terraform and the Terraform action fails.
```

2024-05-10 17:31 UTC, stephaniegalang commented on website/docs/d/kms_kmip_cert.html.markdown
> +  Manages key rings for IBM hs-crypto and KMS.
Should reference cert, not adapter or key ring

2024-05-10 17:31 UTC, stephaniegalang commented on website/docs/d/kms_kmip_cert.html.markdown
> +Retrieves a KMIP Client Certificate from a Key Protect service instance based on the certificate name or ID. The region parameter in the `provider.tf` file must be set. If region parameter is not spe
```suggestion
Retrieves a KMIP Client Certificate from a Key Protect service instance based on the certificate name or ID. The region parameter in the `provider.tf` file must be set. If region parameter is not specified, `us-south` is used by default. If the region in the `provider.tf` file is different from the Key Protect instance, the instance cannot be retrieved by Terraform and the Terraform action fails.
```

2024-05-10 17:31 UTC, stephaniegalang commented on website/docs/d/kms_kmip_certs.html.markdown
> +---
needs fixing

2024-05-10 17:31 UTC, stephaniegalang commented on website/docs/d/kms_kmip_certs.html.markdown
> +Retrieves a list of KMIP Client Certificates from a Key Protect service instance for a given KMIP adapter. The region parameter in the `provider.tf` file must be set. If region parameter is not speci
```suggestion
Retrieves a list of KMIP Client Certificates from a Key Protect service instance for a given KMIP adapter. The region parameter in the `provider.tf` file must be set. If region parameter is not specified, `us-south` is used by default. If the region in the `provider.tf` file is different from the Key Protect instance, the instance cannot be retrieved by Terraform and the Terraform action fails.
```

2024-05-10 17:31 UTC, stephaniegalang commented on website/docs/d/kms_kmip_object.html.markdown
> +---
needs fixing

2024-05-10 17:31 UTC, stephaniegalang commented on website/docs/d/kms_kmip_object.html.markdown
> +Retrieves a KMIP Object from a Key Protect service instance. The region parameter in the `provider.tf` file must be set. If region parameter is not specified, `us-south` is used by default. If the re
```suggestion
Retrieves a KMIP Object from a Key Protect service instance. The region parameter in the `provider.tf` file must be set. If region parameter is not specified, `us-south` is used by default. If the region in the `provider.tf` file is different from the Key Protect instance, the instance cannot be retrieved by Terraform and the Terraform action fails.
```

2024-05-10 17:31 UTC, stephaniegalang commented on website/docs/r/kms_kmip_certs.html.markdown
> +  Manages key rings for IBM hs-crypto and KMS.
needs fixing

2024-05-10 17:31 UTC, stephaniegalang commented on website/docs/r/kms_kmip_adapters.html.markdown
> +---
needs fixing

2024-05-10 17:31 UTC, stephaniegalang commented on website/docs/d/kms_kmip_objects.html.markdown
> +---
needs fixing

2024-05-10 17:31 UTC, stephaniegalang commented on website/docs/d/kms_kmip_objects.html.markdown
> +Retrieves a list of KMIP Objects from a Key Protect service instance for a given KMIP adapter. The region parameter in the `provider.tf` file must be set. If region parameter is not specified, `us-so
```suggestion
Retrieves a list of KMIP Objects from a Key Protect service instance for a given KMIP adapter. The region parameter in the `provider.tf` file must be set. If region parameter is not specified, `us-south` is used by default. If the region in the `provider.tf` file is different from the Key Protect instance, the instance cannot be retrieved by Terraform and the Terraform action fails.
```

2024-05-11 14:01 UTC, hkantare commented on ibm/service/kms/resource_ibm_kms_kmip_adapter.go
> +	instanceID := d.Get("instance_id").(string)
Can you set d.SetID as combination of instance_id and adapter_id separated by "/" 
We can't do d.Get() in read method. 
Import scenario breaks

2024-05-13 10:53 UTC, hkantare commented
Fix conflicts in go.mod

2024-05-16 21:43 UTC, william8siew commented
Follow up PR for this here https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5352/
since i dont have write access, we can close this one later

2024-05-18 04:30 UTC, closed without merging