feat(CIS): Order Advanced Certificate
IBM-Cloud/terraform-provider-ibm pull request #5483
Opened 2024-07-02 22:53 UTC by arjunchauhanibm

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-07-07 00:00 UTC, arjunchauhanibm commented
Testing resource order advanced certificate

<img width="975" alt="image" src="https://github.com/IBM-Cloud/terraform-provider-ibm/assets/157371067/617bba6c-bc8a-4ef4-88bb-1f9bbc31343c">

<img width="1791" alt="image" src="https://github.com/IBM-Cloud/terraform-provider-ibm/assets/157371067/2649d7d0-e48a-4d07-ac44-ce76dc98f7a9">

2024-07-07 00:05 UTC, arjunchauhanibm commented
Testing resource origin certificate

<img width="1790" alt="image" src="https://github.com/IBM-Cloud/terraform-provider-ibm/assets/157371067/178d2bf4-fba1-4d37-98ec-b846936f00b6">

<img width="1097" alt="image" src="https://github.com/IBM-Cloud/terraform-provider-ibm/assets/157371067/56620e47-58bd-442c-b803-c64beafbe690">

<img width="1792" alt="image" src="https://github.com/IBM-Cloud/terraform-provider-ibm/assets/157371067/16a4724f-50bb-4dd5-ac46-a4a8d869b309">

2024-07-07 00:09 UTC, arjunchauhanibm commented
Testing data origin certificate

<img width="952" alt="image" src="https://github.com/IBM-Cloud/terraform-provider-ibm/assets/157371067/76b65fb6-0e23-4e96-bba4-db6cd9a76352">

<img width="1790" alt="image" src="https://github.com/IBM-Cloud/terraform-provider-ibm/assets/157371067/9cc5797c-e60f-4601-8f49-ae4be4323760">

2024-07-07 00:15 UTC, arjunchauhanibm commented
testing import for origin certificate

<img width="1789" alt="image" src="https://github.com/IBM-Cloud/terraform-provider-ibm/assets/157371067/a3199126-79cd-4af4-950a-7881f815949a">

2024-07-11 22:56 UTC, sheltons commented on ibm/service/cis/data_source_ibm_cis_origin_certificate_order.go
> +				Description: "CIS object id or CRN",
Capitalize ID in this description

2024-07-11 22:57 UTC, sheltons commented on ibm/service/cis/data_source_ibm_cis_origin_certificate_order.go
> +				Description: "certificate id",
```suggestion
				Description: "Certificate ID",
```

2024-07-11 22:58 UTC, sheltons commented on ibm/service/cis/data_source_ibm_cis_origin_certificate_order.go
> +							Description: "certificate id",
```suggestion
							Description: "Certificate ID",
```

2024-07-11 22:58 UTC, sheltons commented on ibm/service/cis/data_source_ibm_cis_origin_certificate_order.go
> +							Description: "certificate type",
```suggestion
							Description: "Certificate type",
```

2024-07-11 22:59 UTC, sheltons commented on ibm/service/cis/data_source_ibm_cis_origin_certificate_order.go
> +							Description: "validity days",
```suggestion
							Description: "Validity days",
```

2024-07-11 22:59 UTC, sheltons commented on ibm/service/cis/data_source_ibm_cis_origin_certificate_order.go
> +							Description: "validity days",
```suggestion
							Description: "Validity days",
```

2024-07-11 23:00 UTC, sheltons commented on ibm/service/cis/data_source_ibm_cis_origin_certificate_order.go
> +							Description: "certificate id",
```suggestion
							Description: "Certificate ID",
```

2024-07-11 23:00 UTC, sheltons commented on ibm/service/cis/data_source_ibm_cis_origin_certificate_order.go
> +							Description: "certificate id",
```suggestion
							Description: "Certificate ID",
```

2024-07-11 23:00 UTC, sheltons commented on ibm/service/cis/data_source_ibm_cis_origin_certificate_order.go
> +							Description: "certificate id",
```suggestion
							Description: "Certificate ID",
```

2024-07-11 23:02 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_advanced_certificate_pack_order.go
> +				Description: "CIS object id or CRN",
```suggestion
				Description: "CIS object ID or CRN",
```

2024-07-11 23:02 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_advanced_certificate_pack_order.go
> +				Description: "certificate id",
```suggestion
				Description: "Certificate ID",
```

2024-07-11 23:02 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_advanced_certificate_pack_order.go
> +				Description: "certificate type",
```suggestion
				Description: "Certificate type",
```

2024-07-11 23:06 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_advanced_certificate_pack_order.go
> +				Description: "Hosts which certificate need to be ordered",
```suggestion
				Description: "Hosts for which certificates need to be ordered",
```

2024-07-11 23:06 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_advanced_certificate_pack_order.go
> +				Description: "certificate status",
```suggestion
				Description: "Certificate status",
```

2024-07-11 23:06 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_advanced_certificate_pack_order.go
> +				Description: "validation method",
```suggestion
				Description: "Validation method",
```

2024-07-11 23:18 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_advanced_certificate_pack_order.go
> +				Description: "validity days",
```suggestion
				Description: "Validity days",
```

2024-07-11 23:18 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_advanced_certificate_pack_order.go
> +				Description: "certificate authority",
```suggestion
				Description: "Certificate authority",
```

2024-07-11 23:18 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_advanced_certificate_pack_order.go
> +				Description: "cloudflare branding",
```suggestion
				Description: "Cloudflare branding",
```

2024-07-11 23:19 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_advanced_certificate_pack_order.go
> +		log.Println("Error in reading certificate id")
```suggestion
		log.Println("Error in reading certificate ID")
```

2024-07-11 23:20 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_origin_certificate_order.go
> +				Description: "CIS object id or CRN",
```suggestion
				Description: "CIS object ID or CRN",
```

2024-07-11 23:20 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_origin_certificate_order.go
> +				Description: "certificate id",
```suggestion
				Description: "Certificate ID",
```

2024-07-11 23:20 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_origin_certificate_order.go
> +				Description: "certificate type",
```suggestion
				Description: "Certificate type",
```

2024-07-11 23:21 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_origin_certificate_order.go
> +				Description: "Hosts which certificate need to be ordered",
```suggestion
				Description: "Hosts for which certificates need to be ordered",
```

2024-07-11 23:21 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_origin_certificate_order.go
> +				Description: "validity days",
```suggestion
				Description: "Validity days",
```

2024-07-11 23:21 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_origin_certificate_order.go
> +				Description: "validity days",
```suggestion
				Description: "Validity days",
```

2024-07-11 23:21 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_origin_certificate_order.go
> +				Description: "certificate id",
```suggestion
				Description: "Certificate ID",
```

2024-07-11 23:22 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_origin_certificate_order.go
> +				Description: "certificate id",
```suggestion
				Description: "Certificate ID",
```

2024-07-11 23:22 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_origin_certificate_order.go
> +				Description: "certificate id",
```suggestion
				Description: "Certificate ID",
```

2024-07-11 23:22 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_origin_certificate_order.go
> +		log.Printf("Origin Certificate  order failed: %v", resp)
```suggestion
		log.Printf("Origin Certificate order failed: %v", resp)
```

2024-07-11 23:23 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_origin_certificate_order.go
> +		log.Println("Error in reading certificate id")
```suggestion
		log.Println("Error in reading certificate ID")
```

2024-07-11 23:23 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_origin_certificate_order.go
> +		log.Println("Error in reading certificate id")
```suggestion
		log.Println("Error in reading certificate ID")
```

2024-07-11 23:24 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_origin_certificate_order.go
> +		log.Println("Error in reading certificate id")
```suggestion
		log.Println("Error in reading certificate ID")
```

2024-07-11 23:24 UTC, sheltons commented on ibm/service/cis/resource_ibm_cis_origin_certificate_order.go
> +		log.Println("Error in reading certificate id")
```suggestion
		log.Println("Error in reading certificate ID")
```

2024-07-11 23:26 UTC, sheltons commented on website/docs/d/cis_origin_certificates
> +Retrieve an information of an existing IBM Cloud Internet Services certificates resource. For more information about CIS origin certificate, refer to [managing origin certificates](https://cloud.ibm.
```suggestion
Retrieve the information of an existing IBM Cloud Internet Services certificates resource. For more information about CIS origin certificates, refer to [managing origin certificates](https://cloud.ibm.com/docs/cis?topic=cis-cis-origin-certificates).
```

2024-07-11 23:34 UTC, sheltons commented on website/docs/d/cis_origin_certificates
> +- `certificate_id` - (Optional, String) The ID of the certificate. If ID is not provided you will get the list of certificates. If ID is provided then you will get the information of the particular c
```suggestion
- `certificate_id` - (Optional, String) The ID of the certificate. If the ID is not provided, you will get the list of certificates. If the ID is provided, then you will get the information of that certificate.
```

2024-07-11 23:50 UTC, sheltons commented on website/docs/d/cis_origin_certificates
> +In addition to all argument reference list, you can access the following attribute references after your data source is created.
```suggestion
In addition to the argument reference list, you can access the following attribute references after your data source is created. 
```

2024-07-11 23:50 UTC, sheltons commented on website/docs/d/cis_origin_certificates
> +   - `expires_on` - (String) Expiry date of the certificate.
```suggestion
   - `expires_on` - (String) Expiration date of the certificate.
```

2024-07-11 23:51 UTC, sheltons commented on website/docs/r/cis_advanced_certificate_pack_order.html.markdown
> +  Provides a IBM CIS certificate order resource.
```suggestion
  Provides an IBM CIS certificate order resource.
```

2024-07-11 23:56 UTC, sheltons commented on website/docs/r/cis_advanced_certificate_pack_order.html.markdown
> + Provides an IBM Cloud Internet Services advanced certificate order resource. This resource is associated with an IBM Cloud Internet Services instance and a CIS domain resource. It allows to order an
```suggestion
 Provides an IBM Cloud Internet Services advanced certificate order resource. This resource is associated with an IBM Cloud Internet Services instance and a CIS domain resource. It allows you to order and delete dedicated advanced certificates of a domain of a CIS instance. For more information about CIS certificate ordering, see [managing edge certificates](https://cloud.ibm.com/docs/cis?topic=cis-managing-edge-certs).
```

2024-07-11 23:57 UTC, sheltons commented on website/docs/r/cis_advanced_certificate_pack_order.html.markdown
> +- `cloudflare_branding` - (Optional, Boolean) Whether or not to add Cloudflare Branding for the order.
```suggestion
- `cloudflare_branding` - (Optional, Boolean) Whether to add Cloudflare branding for the order.
```

2024-07-11 23:58 UTC, sheltons commented on website/docs/r/cis_advanced_certificate_pack_order.html.markdown
> +In addition to all argument reference list, you can access the following attribute reference after your resource is created.
```suggestion
In addition to the argument reference list, you can access the following attribute reference after your resource is created.
```

2024-07-11 23:59 UTC, sheltons commented on website/docs/r/cis_advanced_certificate_pack_order.html.markdown
> +- `id` - (String) The record ID. It is a combination of `<certificate_id>,<domain_id>,<cis_id>` attributes concatenated with `:`.
```suggestion
- `id` - (String) The record ID, which is a combination of `<certificate_id>,<domain_id>,<cis_id>` attributes concatenated with `:`.
```

2024-07-11 23:59 UTC, sheltons commented on website/docs/r/cis_origin_certificate_order.html.markdown
> +  Provides a IBM CIS origin certificate order resource.
```suggestion
  Provides an IBM CIS origin certificate order resource.
```

2024-07-12 00:00 UTC, sheltons commented on website/docs/r/cis_origin_certificate_order.html.markdown
> + Provides an IBM Cloud Internet Services origin certificate order resource. This resource is associated with an IBM Cloud Internet Services instance and a CIS domain resource. It allows to order and
```suggestion
Provides an IBM Cloud Internet Services origin certificate order resource. This resource is associated with an IBM Cloud Internet Services instance and a CIS domain resource. It allows you to order and delete dedicated advanced certificates of a domain of a CIS instance. For more information about CIS certificate ordering, see [managing origin certificates](https://cloud.ibm.com/docs/cis?topic=cis-cis-origin-certificates).
```

2024-07-12 00:02 UTC, sheltons commented on website/docs/r/cis_origin_certificate_order.html.markdown
> +` and `keyless-certificate`.
```suggestion

```

2024-07-12 00:02 UTC, sheltons commented on website/docs/r/cis_origin_certificate_order.html.markdown
> +- `request_type` - (Required, String) The type of the certificate. Allowed values are `origin-rsa`, `origin-ecc
```suggestion
- `request_type` - (Required, String) The type of the certificate. Allowed values are `origin-rsa`, `origin-ecc` and `keyless-certificate`.
```

2024-07-12 00:03 UTC, sheltons commented on website/docs/r/cis_origin_certificate_order.html.markdown
> +In addition to all argument reference list, you can access the following attribute reference after your resource is created.
```suggestion
In addition to the argument reference list, you can access the following attribute reference after your resource is created.
```

2024-07-12 00:28 UTC, sheltons commented on website/docs/r/cis_origin_certificate_order.html.markdown
> +- `id` - (String) The record ID. It is a combination of `<certificate_id>,<domain_id>,<cis_id>` attributes concatenated with `:`.
```suggestion
- `id` - (String) The record ID, which is a combination of `<certificate_id>,<domain_id>,<cis_id>` attributes concatenated with `:`.
```

2024-07-12 00:29 UTC, sheltons commented on website/docs/r/cis_origin_certificate_order.html.markdown
> +The `ibm_cis_origin_certificate_order` resource can be imported using the ID. The ID is formed from the certificate ID, the domain ID of the domain and the CRN  Concatenated  by using a `:` character
```suggestion
The `ibm_cis_origin_certificate_order` resource can be imported using the ID. The ID is formed from the certificate ID, the domain ID of the domain, and the CRN  Concatenated  by using a `:` character.
```

2024-07-12 00:33 UTC, sheltons commented on website/docs/r/cis_origin_certificate_order.html.markdown
> +- **Domain ID** is a 32 digit character string of the form: `9caf68812ae9b3f0377fdf986751a78f`
```suggestion
- **Domain ID** is a 32-digit character string of the form: `9caf68812ae9b3f0377fdf986751a78f`
```

2024-07-12 00:33 UTC, sheltons commented on website/docs/r/cis_origin_certificate_order.html.markdown
> +- **CRN** is a 120 digit character string of the form: `crn:v1:bluemix:public:internet-svcs:global:a/4ea1882a2d3401ed1e459979941966ea:31fa970d-51d0-4b05-893e-251cba75a7b3::`
```suggestion
- **CRN** is a 120-digit character string of the form: `crn:v1:bluemix:public:internet-svcs:global:a/4ea1882a2d3401ed1e459979941966ea:31fa970d-51d0-4b05-893e-251cba75a7b3::`
```

2024-07-12 00:33 UTC, sheltons commented on website/docs/r/cis_origin_certificate_order.html.markdown
> +- **Certificate ID** is a 48 digit character string of the form: `484582976896327736468082847548136290560450732393`.
```suggestion
- **Certificate ID** is a 48-digit character string of the form: `484582976896327736468082847548136290560450732393`.
```

2024-07-12 00:34 UTC, sheltons commented on ibm/service/cis/data_source_ibm_cis_origin_certificate_order.go
> +				Description: "CIS object id or CRN",
```suggestion
				Description: "CIS object ID or CRN",
```

2024-07-12 00:36 UTC, sheltons requested changes
I've left comments/suggestions throughout.

2024-07-17 12:16 UTC, hkantare commented
Fix the conflict in go.sum

2024-07-22 07:56 UTC, hkantare approved these changes

2024-07-22 11:17 UTC, hkantare approved these changes

2024-07-22 11:17 UTC, merged