feat(CIS): Origin Post Quantum Encryption and Max HTTP Version
IBM-Cloud/terraform-provider-ibm pull request #5504
Opened 2024-07-11 23:20 UTC by arjunchauhanibm

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2024-07-15 14:44 UTC, sheltons commented on website/docs/r/cis_domain_settings.html.markdown
> +- `origin_post_quantum_encryption` - (Optional, String) Weather to use Post-Quantum key agreement algorithms when connecting to the origin. Supported values are `off`, `preferred` and `supported`.
```suggestion
- `origin_post_quantum_encryption` - (Optional, String) Whether to use post-quantum key agreement algorithms when connecting to the origin. Supported values are `off`, `preferred`, and `supported`.
```

2024-07-15 14:45 UTC, sheltons commented on website/docs/r/cis_domain_settings.html.markdown
>  In addition to all argument reference list, you can access the following attribute reference after your resource is created.
```suggestion
In addition to the argument reference list, you can access the following attribute reference after your resource is created.
```

2024-07-15 14:45 UTC, sheltons requested changes
Comments inline

2024-08-16 13:36 UTC, hkantare commented on ibm/service/cis/resource_ibm_cis_domain_settings.go
> +				Description: "origin_max_http_version setting",
Can we have some valid description

2024-08-16 13:36 UTC, hkantare commented
Fix the conflicts

2024-08-16 13:36 UTC, hkantare commented
Add respective testcase and test results

2024-08-17 03:41 UTC, arjunchauhanibm commented
Test case 1.
origin_max_http_version = "1"
origin_post_quantum_encryption = "off"

<img width="1330" alt="image" src="https://github.com/user-attachments/assets/b62d1e82-6b63-4c9d-afb1-2c2b0ee6fb8a">

<img width="1779" alt="image" src="https://github.com/user-attachments/assets/3fa25cbc-ebb9-4d76-8db0-039c6a009e88">

2024-08-17 03:46 UTC, arjunchauhanibm commented
Test case 2.
origin_max_http_version = "2"
origin_post_quantum_encryption = "preferred"

![image](https://github.com/user-attachments/assets/a36e3b32-4b97-4def-85b6-46e98a41ef75)

2024-08-17 03:48 UTC, arjunchauhanibm commented
Test case 3.
origin_max_http_version = "2"
origin_post_quantum_encryption = "supported"

2024-08-20 12:38 UTC, merged