[Datasource] Add host reference to power dedicated host data sources
IBM-Cloud/terraform-provider-ibm pull request #5834
Opened 2024-12-03 20:49 UTC by Alexander-Kita

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

pi_host (d)
```
=== RUN   TestAccIBMPIHostDataSourceBasic
--- PASS: TestAccIBMPIHostDataSourceBasic (82.79s)
PASS
```

pi_hosts (d)
```
=== RUN   TestAccIBMPIHostsDataSourceBasic
--- PASS: TestAccIBMPIHostsDataSourceBasic (80.24s)
PASS
```

2024-12-04 11:35 UTC, yussufsh requested changes
Can we update the doc as well with this new attribute?

2024-12-04 15:16 UTC, Alexander-Kita commented
@yussufsh Added and fixed some spacing in dedicated host docs

2024-12-04 21:25 UTC, ismirlia approved these changes

2024-12-18 05:06 UTC, yussufsh approved these changes

2024-12-18 05:06 UTC, merged