[SCC]: Updating Terraform with ACS update
IBM-Cloud/terraform-provider-ibm pull request #5891
Opened 2024-12-20 20:34 UTC by tyao117

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

2025-02-19 08:44 UTC, pavanm87 approved these changes
LGTM

2025-02-19 23:15 UTC, ashpc requested changes

2025-02-19 23:15 UTC, ashpc commented on ibm/service/scc/data_source_ibm_scc_scope.go
> +			Identifier:                 "scope_id",
Not a valid key in scope object outside properties

2025-02-19 23:15 UTC, ashpc commented on ibm/service/scc/data_source_ibm_scc_scope.go
> +	getScopeOptions.SetScopeID(d.Get("scope_id").(string))
This should be id not scope_id

2025-02-19 23:15 UTC, ashpc commented on ibm/service/scc/resource_ibm_scc_instance_settings.go
> +	time.Sleep(5 * time.Second)
Why is there a delay here ?

2025-02-19 23:15 UTC, ashpc commented on ibm/service/scc/resource_ibm_scc_profile_attachment.go
> +	if modelMap["environment"] != nil && modelMap["environment"].(string) != "" {
Why are we doing only for environment as there can be other properties as well right ?

2025-02-19 23:15 UTC, ashpc commented on ibm/service/scc/resource_ibm_scc_profile_attachment.go
> +func resourceIbmSccProfileAttachmentPropertyItemToMap(model securityandcompliancecenterapiv3.ScopePropertyIntf) (map[string]interface{}, error) {
Should be similar to other functions in other files above

2025-02-19 23:15 UTC, ashpc commented on ibm/service/scc/resource_ibm_scc_scope.go
> +						"account_id": &schema.Schema{
Allowed properties are 
scope_id
scope_type
exclusions
provider_type
provider_type_instance_id

Let's use only these and no where should we reference ibm_facts_api_instance_id

2025-02-19 23:15 UTC, ashpc commented on ibm/service/scc/resource_ibm_scc_scope.go
> +						"account_id": &schema.Schema{
This is again key value pair

{
					"name": "exclusions",
					"value": [
						{
							"scope_id": "1e351d2203ba44cb8a8bbe971fff7771",
							"scope_type": "enterprise.account_group"
						}
					]
				}

2025-02-19 23:15 UTC, ashpc commented on ibm/service/scc/resource_ibm_scc_scope.go
> +			"scope_id": &schema.Schema{
Not valid property

2025-02-19 23:15 UTC, ashpc commented on ibm/service/scc/resource_ibm_scc_scope.go
> +	} else if id, ok := modelMap["resource_group_id"]; ok && id != "" {
Properties are not right

2025-02-19 23:15 UTC, ashpc commented on ibm/service/scc/resource_ibm_scc_scope.go
> +				case "scope_id":
not a valid key

2025-02-19 23:15 UTC, ashpc commented on ibm/service/scc/resource_ibm_scc_scope.go
> +	saveState := map[string]interface{}{
Not right keys

2025-02-19 23:15 UTC, ashpc commented on ibm/service/scc/resource_ibm_scc_scope.go
> +	case "ibm_cloud_facts_api":
not a valid key

2025-02-19 23:15 UTC, ashpc commented on website/docs/d/scc_scope.html.markdown
> +* `scope_id` - (Required, Forces new resource, String) THe ID of the SCC instance scope in a particular region.
This is an ID created when scope is done and should be id not scope_id

2025-02-19 23:15 UTC, ashpc commented on website/docs/d/scc_scope.html.markdown
> +* `exclusions` - (List) A list of excluded targets from the scope.
always property not first level entity

2025-02-19 23:15 UTC, ashpc commented on website/docs/d/scc_scope.html.markdown
> +	* `account_id` - (String) The ID of the account that was excluded.
schema not right

2025-02-19 23:15 UTC, ashpc commented on website/docs/d/scc_scope.html.markdown
> +Nested schema for **properties**:
same here

2025-02-19 23:15 UTC, ashpc commented on website/docs/r/scc_profile_attachment.html.markdown
> +    ibm_facts_api_instance_id = ibm_scc_provider_type_instance.facts_provider_type_instance.provider_type_instance_id
wrong value

2025-02-19 23:15 UTC, ashpc commented on website/docs/r/scc_scope.html.markdown
> +    ibm_facts_api_instance_id = ibm_scc_provider_type_instance.facts_provider_type_instance.provider_type_instance_id
not right value

2025-02-19 23:15 UTC, ashpc commented on website/docs/r/scc_scope.html.markdown
> +    * `account_id` - (Optional, ForceNew, String) The ID of the IBM account ID.
schema is not right

2025-02-19 23:15 UTC, ashpc commented on website/docs/r/scc_scope.html.markdown
> +* `scope_id` - (String) The ID of the scope.
not right key should be id

2025-02-21 03:14 UTC, ashpc commented on ibm/service/scc/data_source_ibm_scc_scope.go
> +						"scope_id": &schema.Schema{
Why are we not following the same pattern as the main property using account.resource_group format ?

2025-02-21 03:14 UTC, ashpc commented on ibm/service/scc/resource_ibm_scc_scope.go
> +						"scope_type": &schema.Schema{
same here

2025-02-21 10:23 UTC, pavanm87 commented on ibm/service/scc/data_source_ibm_scc_control_library_test.go
> +	// controlLibraryVersionGroupLabel := fmt.Sprintf("d755830f-1d83-4fab-b5d5-1dfb2b0dad1%d", acctest.RandIntRange(1, 9))
Remove commented line

2025-02-21 10:32 UTC, pavanm87 commented on ibm/service/scc/data_source_ibm_scc_report.go
> +	if err = d.Set("created_on", flex.DateTimeToString(report.CreatedOn)); err != nil {
this is converting timestamp into a string, may `created_on` is string type in model

2025-02-21 23:22 UTC, tyao117 commented on ibm/service/scc/data_source_ibm_scc_latest_reports.go
> +		modelMap["created_on"] = model.CreatedOn.String()
see https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-types#types for reference

2025-02-21 23:23 UTC, tyao117 commented on ibm/service/scc/data_source_ibm_scc_latest_reports.go
> +func dataSourceIbmSccLatestReportsScopePropertyToMap(model securityandcompliancecenterapiv3.ScopePropertyIntf) (map[string]interface{}, error) {
Talked to you about this in a meeting. Due to our API's having a polymorphic value, it will be hard to comply to the Terraform SDK types: https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-types#types

2025-02-21 23:24 UTC, tyao117 commented on ibm/service/scc/data_source_ibm_scc_profile_attachment.go
> +func dataSourceIbmSccProfileAttachmentPropertyItemToMap(model securityandcompliancecenterapiv3.ScopePropertyIntf) (map[string]interface{}, error) {
same as what was discussed: https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5891#discussion_r1966316697

2025-02-21 23:25 UTC, tyao117 commented on ibm/service/scc/data_source_ibm_scc_report.go
> +func dataSourceIbmSccReportScopePropertyToMap(model securityandcompliancecenterapiv3.ScopePropertyIntf) (map[string]interface{}, error) {
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5891#discussion_r1966316697

2025-02-21 23:32 UTC, tyao117 commented on website/docs/r/scc_scope.html.markdown
> +    * `account_id` - (Optional, ForceNew, String) The ID of the IBM account ID.
The schema of a Terraform resource does not need to be the same as the schema in an openapi doc. If the Terraform code were to have the same exact schema as the openapi spec, the Terraform code will never work. The values are polymorphic and do not have strongly define types in the attributes. Having a schema that is different does not necessitate a simple "schema is not right" comment and should be explained more throughly.

2025-02-21 23:34 UTC, tyao117 commented on website/docs/r/scc_scope.html.markdown
> +* `scope_id` - (String) The ID of the scope.
A terraform resource has a special usage of `id`. If `id` were to be used, it will fail.

2025-02-21 23:40 UTC, tyao117 commented on ibm/service/scc/data_source_ibm_scc_scope.go
> +						"scope_id": &schema.Schema{
we discussed this in a recorded meeting, and it was agreed that the new attributes are acceptable. Please elaborate why there is a sudden need for a change.

2025-02-21 23:40 UTC, tyao117 commented on ibm/service/scc/resource_ibm_scc_scope.go
> +						"scope_type": &schema.Schema{
see https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5891#discussion_r1966324814

2025-02-21 23:42 UTC, tyao117 commented on ibm/service/scc/data_source_ibm_scc_control_library_test.go
> +	// controlLibraryVersionGroupLabel := fmt.Sprintf("d755830f-1d83-4fab-b5d5-1dfb2b0dad1%d", acctest.RandIntRange(1, 9))
done

2025-02-21 23:49 UTC, tyao117 commented on ibm/service/scc/data_source_ibm_scc_scope.go
> +						"scope_id": &schema.Schema{
this is the a sample response of a scope with exclusions:
```json
...
"name": "exclusions",
      "value": [
        {
          "scope_id": "957934c8d570423299a92a7ca7acd334",
          "scope_type": "account.resource_group"
        }
      ]
```
i do not understand the issue of having it defined in the attribute `exclusions`

2025-02-21 23:56 UTC, tyao117 commented on ibm/service/scc/resource_ibm_scc_scope.go
> +						"scope_type": &schema.Schema{
@pavanm87 can you elaborate why defining`scope_type` is incorrect if `scope_type` is being returned from the response? https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5891#discussion_r1966329729

2025-02-25 19:48 UTC, ashpc commented on ibm/service/scc/data_source_ibm_scc_latest_reports.go
> +		modelMap["created_on"] = model.CreatedOn.String()
As confirmed from the schemaTypes there is no date type only TypeString. Hence this should be okay.

2025-02-25 19:55 UTC, ashpc commented on website/docs/d/scc_scope.html.markdown
> +	* `account_id` - (String) The ID of the account that was excluded.
Discussed this and we are using terraform attributes rather than API response

2025-02-25 19:56 UTC, ashpc commented on ibm/service/scc/data_source_ibm_scc_report_resources.go
> -func dataSourceIbmSccReportResourcesPageHRefToMap(model *securityandcompliancecenterapiv3.PageHRef) (map[string]interface{}, error) {
This data source is not being used so no issue here

2025-02-25 19:56 UTC, ashpc commented on ibm/service/scc/data_source_ibm_scc_report_rule.go
> +	if err = d.Set("created_on", flex.DateTimeToString(ruleInfo.CreatedOn)); err != nil {
As confirmed from the schemaTypes there is no date type only TypeString. Hence this should be okay.

2025-02-25 19:56 UTC, ashpc commented on ibm/service/scc/data_source_ibm_scc_report_rule.go
> +	if err = d.Set("updated_on", flex.DateTimeToString(ruleInfo.UpdatedOn)); err != nil {
As confirmed from the schemaTypes there is no date type only TypeString. Hence this should be okay.

2025-02-25 19:57 UTC, ashpc commented on website/docs/d/scc_scope.html.markdown
> +* `exclusions` - (List) A list of excluded targets from the scope.
Discussed this and we are using terraform attributes rather than API response

2025-02-25 19:57 UTC, ashpc commented on website/docs/d/scc_scope.html.markdown
> +* `scope_id` - (Required, Forces new resource, String) THe ID of the SCC instance scope in a particular region.
Discussed this and we are using terraform attributes rather than API response

2025-02-25 19:57 UTC, ashpc commented on ibm/service/scc/resource_ibm_scc_scope.go
> +	case "ibm_cloud_facts_api":
Discussed this and we are using terraform attributes rather than API response

2025-02-25 19:57 UTC, ashpc commented on ibm/service/scc/resource_ibm_scc_scope.go
> +			"scope_id": &schema.Schema{
Discussed this and we are using terraform attributes rather than API response

2025-02-25 20:10 UTC, tyao117 commented on ibm/service/scc/data_source_ibm_scc_report_evaluations.go
> +		modelMap["expected_value"] = fmt.Sprintf("%v", model.ExpectedValue)
expected_value can be an array and string, and the terraform attribute is abiding to a TypeString.

2025-02-28 13:37 UTC, ashpc approved these changes

2025-02-28 13:37 UTC, ashpc commented on ibm/service/scc/data_source_ibm_scc_scope.go
> +			"scope_id": &schema.Schema{
Confirmed that this is not an issue

2025-02-28 13:37 UTC, ashpc commented on ibm/service/scc/resource_ibm_scc_profile_attachment.go
> +	if modelMap["environment"] != nil && modelMap["environment"].(string) != "" {
Should be okay for now

2025-02-28 13:37 UTC, ashpc commented on ibm/service/scc/resource_ibm_scc_profile_attachment.go
> +func resourceIbmSccProfileAttachmentPropertyItemToMap(model securityandcompliancecenterapiv3.ScopePropertyIntf) (map[string]interface{}, error) {
Confirmed and not an issue

2025-02-28 17:00 UTC, merged